### ISSUE TITLE
SCTE management  implementation in the 5.10 release.  Any bugs with large files?

### ISSUE THREAD

**Issue by ffiore1** [awslabs/video-on-demand-on-aws#105]
It is still not clear how you have implemented that in the 5.10 release. Using that, have you noticed any bugs with large files?

I have modified the encode lambda function of your stack to submit a job with esam information, using an additional csv with the cuepoints information specified in the triggering job template.

what we have noticed is that hls works well but not dash. it would seem there is a bug in MediaConvert  managing ESAM with large files. The cuepoints are not added in that scenario. Didn't you experience that?  any alternative strategy?

_Originally posted by @ffiore1 in https://github.com/awslabs/video-on-demand-on-aws/issues/57#issuecomment-696343606_

**Comment by tomnight** [comment]
We haven't hand any issues with large files while testing the latest release, but what is your definition of large?

 This does look a specific issue with the Mediaconvert service. I would recommend opening a support case through the AWS console. (top right drop down on the menu bar when logged in).

**Comment by tomgilman** [comment]
Closing issue.
