### ISSUE TITLE
Avoid media converting for specific mp4 files

### ISSUE THREAD

**Issue by tapanjo92** [awslabs/video-on-demand-on-aws#106]
Let's say If I have an Mp4 file that I don't want to convert and directly put into a destination bucket. Can that be done?

**Comment by tomnight** [comment]
Presumably you want to still get the mediainfo data and the CloudFront URLs generated? If that's the case then you would have to do a couple of things:

1. user the metadata version of the solution and include a flag to enable disable encoding, transocde:false for example.
2. update processing workflow (step functions) to check for the flag and if its set to false call a copy lambda function
3. create a copy lambda function that will:
  * copy the file to the destination 
  * generate the CloudFront URLs
  * update the DyanmoDB with the details.

**Comment by tomgilman** [comment]
Closing this issue.
