### ISSUE TITLE
`encode` Lambda incorrectly uses default settings

### ISSUE THREAD

**Issue by HandsomeMedia** [awslabs/video-on-demand-on-aws#108]
**Describe the bug**
`encode` Lambda with hard-coded defaults overwrites specified MediaConvert template settings, including CMAF `segmentLength` which was my particular issue.

https://github.com/awslabs/video-on-demand-on-aws/blob/f9b59fab658ce86d7f8336786a78b7063de462b9/source/encode/index.js#L60

https://github.com/awslabs/video-on-demand-on-aws/blob/f9b59fab658ce86d7f8336786a78b7063de462b9/source/encode/index.js#L119

https://github.com/awslabs/video-on-demand-on-aws/blob/f9b59fab658ce86d7f8336786a78b7063de462b9/source/encode/index.js#L219

Instead of preserving only custom template settings, the function should also preserve MediaConvert template settings.  I believe this is most easily accomplished by removing the conditional and merging/preserving template settings regardless of if it's custom or set in MediaConvert.  I've created a pull request for this: https://github.com/awslabs/video-on-demand-on-aws/pull/107

**To Reproduce**
- create a CMAF MediaConvert template with segment length 3 seconds
- specify this template in the environment vars and ingest a video

**Expected behavior**
- output should include segment length of 3 seconds, instead of the hard-coded default of 30 seconds.

**Please complete the following information about the solution:**
- [x] Version: 5.1.0
- [x] Region: us-east-1
- [x] Was the solution modified from the version published on this repository?
- [x] If the answer to the previous question was yes, are the changes available on GitHub?
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Comment by tomnight** [comment]
Again thanks for this we will review the PR in the next release.

**Comment by tomgilman** [comment]
Closing this ticket, this was updated in 5.2.
