### ISSUE TITLE
Why does all video by default opens with 0.4MBPS

### ISSUE THREAD

**Issue by tapanjo92** [awslabs/video-on-demand-on-aws#109]
Here id an image for example.
How to open a video directly say 6mbps?
![ts](https://user-images.githubusercontent.com/49943773/95934916-b648d900-0e1d-11eb-9202-44280e69867c.png)

**Comment by tomnight** [comment]
Those are all segments for the 480p preset and should have the same bitrate. You should see .m3u8 files in S3 as well, these are the manifest files for or each preset. You need open these not the .ts files.

Is that what your asking?

**Comment by tomgilman** [comment]
Closing this issue.
