### ISSUE TITLE
Mediainfo Lambda function generates S3 SigV2 traffic

### ISSUE THREAD

**Issue by simis2626** [awslabs/video-on-demand-on-aws#110]
**Describe the bug**
AWS recommends using SigV4 to sign S3 presigned URLs. By default, the mediaInfo lambda function uses SigV2.

**To Reproduce**
Deploy the solution using the provided CloudFormation template.
https://docs.aws.amazon.com/solutions/latest/video-on-demand/template.html

**Expected behavior**
The solution follows best practice and uses SigV4 presignedUrls.

**Please complete the following information about the solution:**
- [x ] Version: [e.g. v1.0.0] v5.1.0
- [ x] Region: [e.g. us-east-1] ap-southeast-2
- [ x] Was the solution modified from the version published on this repository? No, (only in the interests of testing the fix for this issue.
- [ x] If the answer to the previous question was yes, are the changes available on GitHub?
- [ x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? Yes
- [ x] Were there any errors in the CloudWatch Logs? No

**Screenshots**
NA

**Additional context**
AWS recommendation here:
https://docs.aws.amazon.com/general/latest/gr/signing_aws_api_requests.html#signature-versions

**Comment by tomnight** [comment]
thanks for the feedback, we will add this to our backlog.

**Comment by tomgilman** [comment]
Closing as this matches Issue #111 .  Thanks for the feedback!
