### ISSUE TITLE
Please reopen /issues/63

### ISSUE THREAD

**Issue by skawirat** [awslabs/video-on-demand-on-aws#112]
**Describe the bug**
Assistance with investigating a VOD V5.0.0 missing job issue

**To Reproduce**
It occurs at random 

**Expected behavior**

All the details are provided in previous ticket and I have updated the ticket with additional info
https://github.com/awslabs/video-on-demand-on-aws/issues/63

I am logging this new ticket for you to re-open above ticket ( as GitLab doesn't allow me to re-open it)

**Please complete the following information about the solution:**

Provided in https://github.com/awslabs/video-on-demand-on-aws/issues/63

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by tomnight** [comment]
We will re look at the mediainfo lambda function in the next release, in the meantime as per @dscpinheiro  question in the original issue can find out which specific step is showing RED (failed) in the ingest or processing step function and if possible check the CloudWatch log for the specific error?

for example is it the mediainfo step in ingest, and whats the CW log for that lambda show. Or is it the profiler step in the processing step function and what is logged in the profile lambda function cloudwatch logs?

**Comment by skawirat** [comment]
Hi @tomnight 

>for example is it the mediainfo step in ingest, and whats the CW log for that lambda show. 

There was an error in mediaInfo CludWatch which was also represented in the error handler.

The image I attached towards the end of #63 ; 20 days ago contains cloudwatch entries which was captured via a SNS.

If I find any additional details in the batch process i will update #63 with that info as well

Sam

**Comment by tomgilman** [comment]
Closing this issue.  There was a mediainfo update in the most recent release, v5.3.  Is this is still happening, please re-open a ticket.
