### ISSUE TITLE
Media Convert Job is not being triggered

### ISSUE THREAD

**Issue by AnoopBandi** [awslabs/video-on-demand-on-aws#113]
I have uploaded a 4K .mov file in s3 bucket, but the media info job is not getting created, and I can see the below outpu in Cloud Watch Media info logs.

MEDIAINFO OUTPUT::{
	"media": {
		"@ref": "removed",
		"track": [{
			"@type": "General",
			"VideoCount": "1",
			"AudioCount": "1",
			"OtherCount": "1",
			"FileExtension": "removed",
			"Format": "MPEG-4",
			"Format_Profile": "QuickTime",
			"CodecID": "qt  ",
			"CodecID_Version": "0000.02",
			"CodecID_Compatible": "qt  ",
			"FileSize": "14981551616",
			"Duration": "2742.083",
			"OverallBitRate": "43708528",
			"FrameRate": "24.000",
			"FrameCount": "65810",
			"StreamSize": "752273",
			"HeaderSize": "20",
			"DataSize": "14980799363",
			"FooterSize": "752233",
			"IsStreamable": "No",
			"Encoded_Application": "Blackmagic Design DaVinci Resolve Studio",
			"extra": {
				"FileExtension_Invalid": "braw mov mp4 m4v m4a m4b m4p m4r 3ga 3gpa 3gpp 3gp 3gpp2 3g2 k3g jpm jpx mqv ismv isma ismt f4a f4b f4v"
			}
		}, {
			"@type": "Video",
			"StreamOrder": "0",
			"ID": "1",
			"Format": "AVC",
			"Format_Profile": "Main",
			"Format_Level": "5.1",
			"Format_Settings_CABAC": "No",
			"Format_Settings_RefFrames": "2",
			"CodecID": "avc1",
			"Duration": "2742.083",
			"BitRate": "42170328",
			"Width": "3840",
			"Height": "2160",
			"Sampled_Width": "3840",
			"Sampled_Height": "2160",
			"PixelAspectRatio": "1.000",
			"DisplayAspectRatio": "1.778",
			"Rotation": "0.000",
			"FrameRate_Mode": "CFR",
			"FrameRate_Mode_Original": "VFR",
			"FrameRate": "24.000",
			"FrameCount": "65810",
			"ColorSpace": "YUV",
			"ChromaSubsampling": "4:2:0",
			"BitDepth": "8",
			"ScanType": "Progressive",
			"Delay": "3600.000",
			"StreamSize": "14454319343",
			"Language": "en",
			"colour_description_present": "Yes",
			"colour_description_present_Source": "Container",
			"colour_primaries": "BT.709",
			"colour_primaries_Source": "Container",
			"transfer_characteristics_Source": "Container",
			"matrix_coefficients": "BT.709",
			"matrix_coefficients_Source": "Container",
			"extra": {
				"Codec_configuration_box": "avcC"
			}
		}, {
			"@type": "Audio",
			"StreamOrder": "1",
			"ID": "2",
			"Format": "PCM",
			"Format_Settings_Endianness": "Little",
			"Format_Settings_Sign": "Signed",
			"CodecID": "lpcm",
			"Duration": "2742.083",
			"BitRate_Mode": "CBR",
			"BitRate": "1536000",
			"Channels": "2",
			"ChannelPositions": "Front: L R",
			"ChannelLayout": "L R",
			"SamplingRate": "48000",
			"SamplingCount": "131619984",
			"BitDepth": "16",
			"Delay": "3600.000",
			"Delay_DropFrame": "No",
			"Delay_Source": "Container",
			"StreamSize": "526480000",
			"StreamSize_Proportion": "0.03514",
			"Language": "en",
			"Default": "Yes",
			"AlternateGroup": "1"
		}, {
			"@type": "Other",
			"StreamOrder": "2",
			"ID": "3",
			"Type": "Time code",
			"Format": "QuickTime TC",
			"Duration": "2742.083",
			"FrameRate": "24.000",
			"TimeCode_FirstFrame": "01:00:00:00",
			"TimeCode_Striped": "Yes",
			"Language": "en",
			"Default": "No"
		}]
	}
}

I can see the below error after the log

Unsupported: Other

And also received an ingest SNS notification, however, the create Job API is not being triggered

**Comment by AnoopBandi** [comment]
Hi Tom,

Thanks for your reply, 

1)Yes, it has passed all the steps in the Ingest function
2)It happened to only this file
3)I can see that error in Media info logs

thanks in advance

**Comment by tomnight** [comment]
Sorry for the late followup but that sounds like it is specific to that file then.

There is a pull request to update mediainfo (https://github.com/awslabs/video-on-demand-on-aws/pull/116) which we are looking at now, you could try this but I would first  try renaming the file to re trigger the workflow to see if you get the same result.

**Comment by tomgilman** [comment]
Closing this issue, as it seems related to a particular file.
