### ISSUE TITLE
How to convert thumbs into single file?

### ISSUE THREAD

**Issue by bedlate** [awslabs/video-on-demand-on-aws#117]
https://stackoverflow.com/a/59444865

Hi guys, I want to make video preview like Youtube. MediaConvert can capture frame to multiple files. I wonder if there are some settings to make theme into single file.

**Comment by tomnight** [comment]
MediaConvert supports frame capture but not in the way describe in the stacks overflow thread.  You would have to add a process to the publishing steps function to handle this. You could take a look at: https://github.com/lovell/sharp

**Comment by tomgilman** [comment]
Closing this issue.  MediaConvert doesn't support taking multiple images and putting them into a single file.  It does support the other way around of taking a video file and outputting images.
