### ISSUE TITLE
Local development

### ISSUE THREAD

**Issue by tariqinaam** [awslabs/video-on-demand-on-aws#118]
Hi,
I am trying to see if there is any doc help to setup local development. 
I want to make some changes to lamda function and further step to it. 
What's the best way to easily write and test. Thanks

**Comment by tariqinaam** [comment]
I am able to build and deploy with Aws cli. However struggling to see how to write and test some lambda function modification locally.

**Comment by morjoan** [comment]
Hi, 
The recommended way to make function changes and testing them are outlined here: https://github.com/awslabs/video-on-demand-on-aws#creating-a-custom-build. I believe that's what you're doing currently. 
We don't have official support here for doing local lambda testing with this solution. But there are tools outside of the solution that can probably help you do local testing. One is SAM: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-test-and-debug.html

**Comment by tariqinaam** [comment]
> Hi,
> The recommended way to make function changes and testing them are outlined here: https://github.com/awslabs/video-on-demand-on-aws#creating-a-custom-build. I believe that's what you're doing currently.
> We don't have official support here for doing local lambda testing with this solution. But there are tools outside of the solution that can probably help you do local testing. One is SAM: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-test-and-debug.html

Thanks @morjoan, AWS SAM worked quite well with local testing and I am able to deploy using cloudformation. thanks for your help
