### ISSUE TITLE
Error occurred while GetObject. S3 Error Code: NoSuchBucket. S3 Error Message: The specified bucket does not exist 

### ISSUE THREAD

**Issue by SabyasachiRana** [awslabs/video-on-demand-on-aws#120]
Error occurred while GetObject. S3 Error Code: NoSuchBucket. S3 Error Message: The specified bucket does not exist (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 847a6b65-cffa-412b-ba9a-eb4b47b6b209; Proxy: null)

**Comment by satkarph** [comment]
./build-s3-dist.sh my-bucket video-on-demand-on-aws version
in this line you must ignore us-east-1 in ...... my-bucket-us-east-1 i got solved it by doing this

**Comment by SabyasachiRana** [comment]
./build-s3-dist.sh testbucket testott v1.0
this is my command type. still i'm getting error

**Comment by SabyasachiRana** [comment]
Actually I want to use 4k HLS or DASH. My input file is 4k but I want to get 4k HLS or Dash after encoding, but this template have only 1080p,720p,480p options

**Comment by satkarph** [comment]
did you create the bucket name as testbucket-us-east-1. here you need us-east-1
but at build command, you must ignore it. it should be ./build-s3-dist.sh testbucket video-on-demand-on-aws version

**Comment by SabyasachiRana** [comment]
Thanks
