### ISSUE TITLE
How to customise the Cloud Formation template and deploy to AWS?

### ISSUE THREAD

**Issue by ericallam** [awslabs/video-on-demand-on-aws#17]
I've managed to launch the VOD CloudFormation stack on my account and get everything working. I'd like to do some customisation of the code and CloudFormation template to achieve two things: use different presets for MediaConvert to support portrait video and be able to include the MP4 destination bucket in the CloudFront distribution as an origin. I'm looking through the VOD source code and I see there is a build bash script but all it does is zip up the lambda functions and customise the code bucket name in the CloudFormation template. There doesn't seem to be any documentation on what is needed to do once the Lambda functions are zipped up and the template is updated. Do I need to write another script that uploads those lambda functions to an S3 bucket? I could do that but isn't there an issue with the `cfn-response` module not being available to lambda code in an S3 bucket? According to [this](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-code.html#cfn-lambda-function-code-cfnresponsemodule):  _The cfn-response module isn't available for source code that's stored in Amazon S3 buckets. To send responses, write your own functions_.

So that seems like uploading the custom-resources lambda function to S3 won't work? How should the custom-resources lambda function be deployed then?

Any help in this matter would be greatly appreciated.

**Comment by tomnight** [comment]
The build script packages the lambda source code ready to be deployed but doesn't upload the content to s3. CloudFormation requires the source code to be hosted in a S3 bucket in the region you are deploying the template. You'll need to upload the zip files to the bucket that you define when running the build script. For example lets say you want to deploy the code to us-east-1:

1. Create a bucket in us-east-1 called mybucket-us-east-1
2. run the build script `./build-s3-dist.sh mybucket test`
3. upload the zip files: `aws s3 sync dist/ s3://mybucket-us-east-1/video-on-demand/test --acl public-read`
4. deploy the template in us-east-1

If you wanted to add support for another region you could simply sync the content to another bucket: `s3://mybucket-us-west-2/video-on-demand/test/`

Hope this makes sense and we will look to update the documentation to make this more clear for the next release.

**Comment by ericallam** [comment]
Thanks for the instructions, that makes sense!
