### ISSUE TITLE
Add support for portrait videos

### ISSUE THREAD

**Issue by arivera-skycred** [awslabs/video-on-demand-on-aws#28]
Please add support for videos shot in portrait resolutions.

- Include MediaConvert templates for portrait resolutions
- Include support for Rotate parameter

**Comment by tomnight** [comment]
thanks for your feedback, we will add this request to our features roadmap and review it in the next release.

**Comment by RealDrewKlayman** [comment]
We need this as soon as possible please. We are really struggling and we are live.

**Comment by arivera-skycred** [comment]
@RealDrewKlayman If you are willing to help test, you can checkout my fork. I wouldn't deploy to production until you're comfortable with how it behaves. 

https://github.com/arivera-skycred/video-on-demand-on-aws

https://github.com/awslabs/video-on-demand-on-aws/pull/29

**Comment by romcok** [comment]
@arivera-skycred Hi, I'm trying it and it doesn't update my job templates.

**Comment by arivera-skycred** [comment]
@romcok I am not sure if it will work in an update scenario. I tore down the entire CloudFormation deployment and tried from scratch and it worked. The only issue I noticed was with the Encode lambda function. For some reason the Layer that is added during the CloudFormation is not properly utlizing the latest `aws-sdk` which is required for the `Rotate: AUTO` param to work. I had to manually upload the layer for it to work.

**Comment by romcok** [comment]
Uf, thanks, but this is little hard to update.

Do you know where mediaInfo.video[0].rotation comes from? I don't see it in srcMediaInfo. I think it set me the landscape video to portrait because the rotation property is missing.



    event.rotation = mediaInfo.video[0].rotation; // == undefined

    event.isRotated = (event.rotation !== 0 && event.rotation !== 180); // == true

**Comment by romcok** [comment]
Finally it works.
I had to map the rotation attribute to MediaInfo class and change cf custom resource.

**Comment by arivera-skycred** [comment]
@romcok glad it works for you now. It was a tedious update to be sure.

**Comment by dscpinheiro** [comment]
We just released a new version of the solution (v5.0.0 - https://aws.amazon.com/solutions/video-on-demand-on-aws/), and thanks to this PR by @rromanchuk (https://github.com/awslabs/video-on-demand-on-aws/pull/27), you can now specify an _inputRotate_ parameter to the workflow (https://github.com/awslabs/video-on-demand-on-aws#source-metadata-option).
