### ISSUE TITLE
SQS

### ISSUE THREAD

**Issue by kodayashi** [awslabs/video-on-demand-on-aws#3]
Would love the ability to optionally subscribe an SQS queue to the SNS topic.

**Comment by tomnight** [comment]
Thanks for the feedback, we will ad this to the list of feature request. If this is something you need to setup there is a detailed example of how to do this here: 
https://docs.aws.amazon.com/sns/latest/dg/SendMessageToSQS.html

**Comment by rromanchuk** [comment]
@kodayashi whats your strategy on the "last mile" aspect of this work flow.  See my comments https://github.com/awslabs/video-on-demand-on-aws/issues/5#issuecomment-424529671

SQS would be great since i'm already using it my existing stack

**Comment by shsenior** [comment]
Addressed with Version 4.0.0
