### ISSUE TITLE
Encountered Permission Issue in MediaInfo

### ISSUE THREAD

**Issue by fredmararac** [awslabs/video-on-demand-on-aws#32]
After successfully provisioning the resources from the CloudFormation template, I tried to upload a video to test. However, I encountered a permission issue on Media Info step accessing the video from signed S3 url.

Any advise how to fix this?

**Comment by olayer9** [comment]
I have the same problem with custom template generated without important changes with the original (only a new table created)... any solution?

Cause
{
  "errorMessage": "MediaInfo.command: https://videoondemand-source-.....s3.eu-central-1.amazonaws.com/test.mp4?......&X-Amz-SignedHeaders=host'\n/bin/sh: /var/task/bin/mediainfo: Permission denied\n",
  "errorType": "Error",
  "stackTrace": [
    "/bin/sh: /var/task/bin/mediainfo: Permission denied",
    "",
    "ChildProcess.exithandler (child_process.js:275:12)",
    "emitTwo (events.js:126:13)",
    "ChildProcess.emit (events.js:214:7)",
    "maybeClose (internal/child_process.js:925:16)",
    "Socket.stream.socket.on (internal/child_process.js:346:11)",
    "emitOne (events.js:116:13)",
    "Socket.emit (events.js:211:7)",
    "Pipe._handle.close [as _onclose] (net.js:567:12)"
  ]
}


Thanks!

**Comment by tumdav** [comment]
@olayer9 you should make it executable

**Comment by olayer9** [comment]
How? Thank you!

**Comment by tumdav** [comment]
chmod +x FILEPATH

**Comment by georgebearden** [comment]
Closing this issue as the problem was addressed in the comments. Please reach back out if you have other questions.
