### ISSUE TITLE
 support for MediaPackage VOD

### ISSUE THREAD

**Issue by ffiore1** [awslabs/video-on-demand-on-aws#37]
> Hi @ffiore1,
> Yes, we do plan on working on this solution in the next few months. Our main priority for the next 
> release is to add support for MediaPackage VOD and address any outstanding issues (such as the 
> metadata file not overwriting the defaults).

@dscpinheiro that would be very interesting. 

Just trying to use MediaConvert with this stack, but facing few issues with an our partner: their mini set top box seems able to play clips encoded/drm-ed with MediaPackage but not with MediaConvert. Probbly, we might to play around with the Mediaconvert settings.

How might we integrate the two with this solution/stack? We could extend that and use the MP api (create asset etc.) to generate the new asset like we are already curently doing for the live2vod. 

To implement that, going in your same direction, how are you going to do that? .smil file?
https://docs.aws.amazon.com/mediapackage/latest/ug/supported-inputs-vod.html

would you have any beta of that I might start playing with? any indicative deadline for that?

thaks, any help would be really appreciated

**Comment by dscpinheiro** [comment]
Hi @ffiore1,

Our goal is to add MediaPackage VOD as an optional part of the workflow. If enabled, we will use the HLS output of the MediaConvert job as the input for an [asset](https://docs.aws.amazon.com/mediapackage/latest/ug/asset.html).

As I commented on the other issue, it's something we're working on for the next release, but unfortunately we cannot commit to any deadlines. We'll update the repository as soon as it's ready.

**Comment by ffiore1** [comment]
That's great news, so I will use that as some point!

Thanks

**Comment by dscpinheiro** [comment]
Hi @ffiore1,

We just released a new version of the solution (v5.0.0 - https://aws.amazon.com/solutions/video-on-demand-on-aws/), and support for MediaPackage VOD is included.

Please refer to the implementation guide for more details: https://docs.aws.amazon.com/solutions/latest/video-on-demand/welcome.html

**Comment by ffiore1** [comment]
@dscpinheiro I read that you reccomend a new stack for the upgrade to the new release.

we would like to keep the existing data in the Dynamo db table. 

any changes in the db? should we export/import the data? 

which is your advice on that?

**Comment by dscpinheiro** [comment]
We'll write a blog post about this new release, and there will be a section about importing data from a previous version.

In summary, here's what you'd have to do:
- Launch the new version
- Export / import the data from the previous DynamoDB table to the new table (the data changes are described on the changelog file)

We also recommend not deleting the existing stack while you're testing. If you do that, the Dynamo table and CloudFront distribution will be deleted, and the urls on the new table will be broken.

**Comment by ffiore1** [comment]
@dscpinheiro 

sorry I can't find the details you mention about the the data changes which should be described on the changelog file. 

will the export/import work without any  drawbacks?

**Comment by dscpinheiro** [comment]
Hi @ffiore1,

Here's an example of the same file being processed in different versions of the solution:

V4:
```json
{
    "archiveSource": true,
    "cloudFront": "D123456789012.cloudfront.net",
    "dashPlaylist": "s3://vod-v4-destination/random-guid/dash/video.mpd",
    "dashUrl": "https://D123456789012.cloudfront.net/random-guid/dash/video.mpd",
    "destBucket": "vod-v4-destination",
    "ecodeJobId": "job-id",
    "encodingProfile": 1080,
    "EndTime": "2019-12-13 12:03.0",
    "frameCapture": true,
    "frameCaptureHeight": 1080,
    "frameCaptureWidth": 1920,
    "guid": "random-guid",
    "hlsPlaylist": "s3://vod-v4-destination/random-guid/hls/video.m3u8",
    "hlsUrl": "https://D123456789012.cloudfront.net/random-guid/hls/video.m3u8",
    "jobTemplate": "vod-v4_Ott_1080p_Avc_Aac_16x9_qvbr",
    "mp4Outputs": [
        "s3://vod-v4-destination/random-guid/mp4/video_Mp4_Avc_Aac_16x9_1920x1080p_24Hz_6Mbps_qvbr.mp4",
        "s3://vod-v4-destination/random-guid/mp4/video_Mp4_Avc_Aac_16x9_1280x720p_24Hz_4.5Mbps_qvbr.mp4"
    ],
    "mp4Urls": [
        "https://D123456789012.cloudfront.net/random-guid/mp4/video_Mp4_Avc_Aac_16x9_1920x1080p_24Hz_6Mbps_qvbr.mp4",
        "https://D123456789012.cloudfront.net/random-guid/mp4/video_Mp4_Avc_Aac_16x9_1280x720p_24Hz_4.5Mbps_qvbr.mp4"
    ],
    "srcBucket": "vod-v4-source",
    "srcHeight": 1080,
    "srcVideo": "video.mp4",
    "srcWidth": 1920,
    "startTime": "2019-12-13 12:03.3",
    "thumbNail": [
        "s3://vod-v4-destination/random-guid/thumbnails/video_tumb.0000004.jpg"
    ],
    "thumbNailUrl": [
        "https://D123456789012.cloudfront.net/random-guid/thumbnails/video_tumb.0000004.jpg"
    ],
    "workflowName": "vod-v4",
    "workflowStatus": "Complete",
    "workflowTrigger": "Video"
}
```

V5:
```json
{
    "archiveSource": true,
    "cloudFront": "D123456789012.cloudfront.net",
    "dashPlaylist": "s3://vod-v5-destination/random-guid/dash/video.mpd",
    "dashUrl": "https://D123456789012.cloudfront.net/random-guid/dash/video.mpd",
    "destBucket": "vod-v5-destination",
    "enableMediaPackage": false,
    "encodeJobId": "job-id",
    "encodingProfile": 1080,
    "endTime": "2019-12-13T12:03:42.681Z",
    "frameCapture": true,
    "frameCaptureHeight": 1080,
    "frameCaptureWidth": 1920,
    "guid": "random-guid",
    "hlsPlaylist": "s3://vod-v5-destination/random-guid/hls/video.m3u8",
    "hlsUrl": "https://D123456789012.cloudfront.net/random-guid/hls/video.m3u8",
    "inputRotate": "DEGREE_0",
    "isCustomTemplate": false,
    "jobTemplate": "vod-v5_Ott_1080p_Avc_Aac_16x9_qvbr",
    "mp4Outputs": [
        "s3://vod-v5-destination/random-guid/mp4/video_Mp4_Avc_Aac_16x9_1920x1080p_24Hz_6Mbps_qvbr.mp4",
        "s3://vod-v5-destination/random-guid/mp4/video_Mp4_Avc_Aac_16x9_1280x720p_24Hz_4.5Mbps_qvbr.mp4"
    ],
    "mp4Urls": [
        "https://D123456789012.cloudfront.net/random-guid/mp4/video_Mp4_Avc_Aac_16x9_1920x1080p_24Hz_6Mbps_qvbr.mp4",
        "https://D123456789012.cloudfront.net/random-guid/mp4/video_Mp4_Avc_Aac_16x9_1280x720p_24Hz_4.5Mbps_qvbr.mp4"
    ],
    "srcBucket": "vod-v5-source",
    "srcHeight": 1080,
    "srcVideo": "video.mp4",
    "srcWidth": 1920,
    "startTime": "2019-12-13T12:03:00.006Z",
    "thumbNail": [
        "s3://vod-v5-destination/random-guid/thumbnails/video_tumb.0000004.jpg"
    ],
    "thumbNailUrl": [
        "https://D123456789012.cloudfront.net/random-guid/thumbnails/video_tumb.0000004.jpg"
    ],
    "workflowName": "vod-v5",
    "workflowStatus": "Complete",
    "workflowTrigger": "Video"
}
```
