### ISSUE TITLE
Unexpected behaviour while using additional MC template

### ISSUE THREAD

**Issue by ffiore1** [awslabs/video-on-demand-on-aws#38]
hi there,
I have been using your aws vod solution for a while. (https://github.com/awslabs/video-on-demand-on-aws#source-code, https://aws.amazon.com/solutions/video-on-demand-on-aws/
 
I am creating metadata json files to trigger workflows.
{"srcVideo": "02067ab9-953a-4764-9683-5638d93e14d3", "jobTemplate": "VOD-25fps-DRM", "priority": 50, "archiveSource": false, "frameCapture": false, "qvbr": true, "StatusUpdateInterval": "SECONDS_60", "accelerationSettings": {"Mode": "ENABLED"}}.

attached my own MC templates I am using for   this. 

we verified that the dash version (not the hls) was generated with unexpected segment length ( 30 secs vs 6 secs) despite the template settings (attached), adding also the dynamo db record for this job and the generated mpd.

[aws-mediaconvert-job-1570075372526-rrcqr6.json.zip](https://github.com/awslabs/video-on-demand-on-aws/files/3684673/aws-mediaconvert-job-1570075372526-rrcqr6.json.zip)
[MediaConvert-25fps-DRM.zip](https://github.com/awslabs/video-on-demand-on-aws/files/3684674/MediaConvert-25fps-DRM.zip)
[dydb-record.zip](https://github.com/awslabs/video-on-demand-on-aws/files/3684677/dydb-record.zip)

Any idea on this? Your advice? 

Additionally, do you advice to change your own MC templates or just add new ones?   
Ideally, as we did, I would prefer just to add them so that we do not modify your solution at all, just putting a wrapper on it.
[4a36aeda-6aaa-4a6c-9a3e-45b3c3c9bd8b.mpd.zip](https://github.com/awslabs/video-on-demand-on-aws/files/3684716/4a36aeda-6aaa-4a6c-9a3e-45b3c3c9bd8b.mpd.zip)

**Comment by dscpinheiro** [comment]
Hi @ffiore1,

Yes, the recommended approach is to create new templates so that you can manage them separately of the solution.

I was looking at the files you sent and I have a question: The _aws-mediaconvert-job-1570075372526-rrcqr6_ refers to the _Optus_VOD_25fps_ JobTemplate, but the metadata example you gave shows that the actual template used was _VOD-Fetch-25fps-DRM_ (which can be confirmed by looking at the DynamoDB record). 

Are they (_Optus_VOD_25fps_ and _VOD-Fetch-25fps-DRM_) supposed to be the same?

**Comment by ffiore1** [comment]
Yes pretty much, i added the wrong ones but they are pretty identical apart from minor setting

Sent from my Samsung GALAXY S5
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ffiore1** [comment]
sorry I was not  precise. 

the attached metadata template is exactly similar to the one we used with the desired, final MC template (Optus_VOD_25fps). CamelCase, etc. (by the way, the frequency status update does not seem to work very well, the sns are not triggered very often.)

The other MC template we tried (VOD-Fetch-25fps-DRM) was the one with UNENCRYPTED_SEI setting. in terms of workflow, exactly the same. (metatadata file triggered). 

Additionally, when we tried to export manually presets&template and import them in another environment(while working on the automation), that did not work properly: still investigating why. Just wondering if that may be caused by a wrong template setting/configuration which might also cause the wrong drm dash processing (30 seconds chunk). 

if there is anything you might need for the investigation, please let me know.

**Comment by dscpinheiro** [comment]
The SNS notification is only sent when the job completes or fails, so the the status update is probably working correctly, but the CloudWatch Event Rule (which triggers the SNS topic) is not invoked if the status is different that ERROR or COMPLETE.

Please let us know if you find the issue when importing the template. We'd have to do more investigating, but your theory that some invalid setting is causing MediaConvert not to use your template sounds reasonable.

**Comment by dscpinheiro** [comment]
@ffiore1,

I was just double-checking the _aws-mediaconvert-job-1570075372526-rrcqr6_ file and I'm a bit confused about something: where did you specify the segment length to be 6?

I see this section, which would explain why the segment is being generated with 30s:

```
{
    "OutputGroupSettings": {
        "Type": "DASH_ISO_GROUP_SETTINGS",
        "DashIsoGroupSettings": {
            "SegmentLength": 30,
            "FragmentLength": 3
        }
    }
}
```

**Comment by ffiore1** [comment]
by the way, using the same templates and triggering the jonb via the MC  console, that works well

**Comment by dscpinheiro** [comment]
If it works via the console, it should work via the solution too.

Here's something you can do to troubleshoot:
- Trigger two jobs (one via the console and another via the solution) using the same template and source input
- Compare them using the CLI (replacing the _region-name-1_, _abcd1234_, _id-of-job1_ and _id-of-job2_ values)
```
aws mediaconvert get-job \
    --endpoint-url https://abcd1234.mediaconvert.region-name-1.amazonaws.com \
    --region region-name-1 \
    --id id-of-job1 > job1.json

aws mediaconvert get-job \
    --endpoint-url https://abcd1234.mediaconvert.region-name-1.amazonaws.com \
    --region region-name-1 \
    --id id-of-job2 > job2.json
```

**Comment by dscpinheiro** [comment]
@ffiore1,

I was able to reproduce the problem. Here's what I did:
- Created a custom template by duplicating one of the files provided by the solution (__Ott_1080p_Avc_Aac_16x9_qvbr_)
- Kept all settings the same, except for _SegmentLength_ and _FragmentLength_
- Created a job with this new template using the console -> settings were applied correctly
- Updated a metadata file to the S3 bucket specifying the new template -> settings were not applied

I'll update this issue as soon as I have more information.

**Comment by ffiore1** [comment]
thanks.

about the update interval, if we want more frequent updates, we should then query directly the dynamodb table. is that right?

**Comment by dscpinheiro** [comment]
No, the DynamoDB table is only updated when the job is completed (successfully or not). 

What you could do is create another CloudWatch Events Rule that has the desired status (e.g. PROGRESSING) in the event pattern and the SNS topic as a target.

**Comment by ffiore1** [comment]
well, I already did that. even in this case it seems that the updates are not that frequent


getting all the status values and processing all of them

using 2 additional sns

1) sns
{ "source": [ "aws.mediaconvert" ] }

2) sns

{ "source": [ "aws.mediaconvert" ], "detail": { "userMetadata": { "workflow": [ "VOD" ] } } }



________________________________

**Comment by ffiore1** [comment]
> @ffiore1,
> 
> I was able to reproduce the problem. Here's what I did:
> 
> * Created a custom template by duplicating one of the files provided by the solution (__Ott_1080p_Avc_Aac_16x9_qvbr_)
> * Kept all settings the same, except for _SegmentLength_ and _FragmentLength_
> * Created a job with this new template using the console -> settings were applied correctly
> * Updated a metadata file to the S3 bucket specifying the new template -> settings were not applied
> 
> It looks like it's because some values are hard-coded in the [encode function](https://github.com/awslabs/video-on-demand-on-aws/blob/master/source/encode/index.js#L33), but I'll update this issue as soon as I have more information.

Ok, thanks. we are planning to go live soon. So, it would be great if we could some advice on it:
- change ourselves the code in the encode function 
- have a fix for that.

I understand that the 30 seconds is pretty standard for VOD content but on some specific devices/set top boxes content encoded that way did not play well probably due to devices power(memory/cpu) limitations. On the contrary, 6 or 4 seconds encoded play well. Any advice on this? We would change 30 to 6
https://github.com/awslabs/video-on-demand-on-aws/blob/master/source/encode/index.js#L98

**Comment by dscpinheiro** [comment]
Hi @ffiore1,

We'll include the fix in the next release, but here's how you can change it:

- Update the profiler function (last section before the catch statement) to add a new property to the event:
```javascript
// source/profiler/index.js
if (!event.jobTemplate) {
    // Existing code
    event.isCustomTemplate = false;
} else {
    event.isCustomTemplate = true;
}
```

- Install [lodash](https://www.npmjs.com/package/lodash) in the encode directory:
```console
cd source/encode/
npm i lodash
```

- Update the encode function (the section that populates the job's OutputGroups) to check if _isCustomTemplate_ is true, and if that's the case, merge the custom settings with the defaults provided:
```javascript
// source/encode/index.js
const _ = require('lodash');

const applySettingsIfNeeded = (isCustomTemplate, originalGroup, customGroup) => {
    if (isCustomTemplate) {
        return _.merge({}, originalGroup, customGroup);
    }

    return originalGroup;
};

exports.handler = async (event) => {
    // Existing code

    let tmpl = await mediaconvert.getJobTemplate({ Name: event.jobTemplate }).promise();
    console.log(`TEMPLATE:: ${JSON.stringify(tmpl, null, 2)}`);

    tmpl.JobTemplate.Settings.OutputGroups.forEach(group => {
        let found = false, defaultGroup = {};

        if (group.OutputGroupSettings.Type === 'FILE_GROUP_SETTINGS') {
            found = true;
            defaultGroup = mp4;
        }

        if (group.OutputGroupSettings.Type === 'HLS_GROUP_SETTINGS') {
            found = true;
            defaultGroup = hls;
        }

        if (group.OutputGroupSettings.Type === 'DASH_ISO_GROUP_SETTINGS') {
            found = true;
            defaultGroup = dash;
        }

        if (group.OutputGroupSettings.Type === 'MS_SMOOTH_GROUP_SETTINGS') {
            found = true;
            defaultGroup = mss;
        }

        if (group.OutputGroupSettings.Type === 'CMAF_GROUP_SETTINGS') {
            found = true;
            defaultGroup = cmaf;
        }

        if (found) {
            console.log(`${group.Name} found in Job Template`);

            const outputGroup = applySettingsIfNeeded(event.isCustomTemplate, defaultGroup, group);
            job.Settings.OutputGroups.push(outputGroup);
        }
    });
    
    // Existing code
};
```

After applying these changes, the workflow should use your provided custom settings.

**Comment by ffiore1** [comment]
@dscpinheiro  @team

thanks for the patch, very much appreciated.

I amended the files, do you mean something like this?see attachments. 


thanks again

[profiler-index.js.zip](https://github.com/awslabs/video-on-demand-on-aws/files/3699267/profiler-index.js.zip)
[encode_index.js.zip](https://github.com/awslabs/video-on-demand-on-aws/files/3699268/encode_index.js.zip)

**Comment by ffiore1** [comment]
amended, seem to work.

will  test them properly tomorrow.

keep you posted....


[encode-index.js.zip](https://github.com/awslabs/video-on-demand-on-aws/files/3701993/encode-index.js.zip)
[profiler-index.js.zip](https://github.com/awslabs/video-on-demand-on-aws/files/3701994/profiler-index.js.zip)

**Comment by dscpinheiro** [comment]
Almost, on the encode file, you should remove lines 225 - 260. 

You only need one forEach (which is already defined on line 188).

**Comment by ffiore1** [comment]
> Almost, on the encode file, you should remove lines 225 - 260.
> 
> You only need one forEach (which is already defined on line 188).

I was too slow to post after the real changes/tests and you were very quick.

Thanks for that.

**Comment by ffiore1** [comment]
Hi @dscpinheiro ,
after the advised change, the template second thing is working. The acceleration, the priority and the queue not (as previously).

Are we using an incorrect template? Or does the solution not manage those (acceleration, queue)? 

Francesco

{"srcVideo":"DIG_ARS_TOT_ANALYSIS_1.mp4", "jobTemplate": " VOD_25fps", "priority": 50, "archiveSource": false, "frameCapture": false, "qvbr": true, "StatusUpdateInterval": "SECONDS_10", "accelerationSettings": {"Mode": "ENABLED"}, "queue": "arn:aws:mediaconvert:ap-southeast-2:478765186332:queues/VodQueue"}

**Comment by dscpinheiro** [comment]
Hi @ffiore1,

No, the solution does not manage these settings; it assumes anything other than the properties defined in the [README file](https://github.com/awslabs/video-on-demand-on-aws#source-metadata-option) are additional metadata to be stored in Dynamo.

Here's what you can do to use different settings:
- Create a custom template
- Update the job settings to your desired values
<img width="682" alt="media-convert" src="https://user-images.githubusercontent.com/3842788/66509027-3a94ad80-eaa0-11e9-86fc-7cd32ec6a813.png">
- Specify this new template in the 'jobTemplate' property of the metadata file

**Comment by ffiore1** [comment]
Hi @dscpinheiro 
thanks for your reply.

Initially I thougth the same and created the attached template, but when the job runs it does not use the chosen queue but the default one.

Can that be a MP issue or solution issue?

Thanks
 Francesco
[Template.json.zip](https://github.com/awslabs/video-on-demand-on-aws/files/3709578/Template.json.zip)
[job.json.zip](https://github.com/awslabs/video-on-demand-on-aws/files/3709579/job.json.zip)

**Comment by ffiore1** [comment]
additionally, the acceleration does not work, getting this errors, even if I set up the timecode to start at 0

![Screen Shot 2019-10-10 at 9 14 58 am](https://user-images.githubusercontent.com/18639230/66524587-931a8800-eb3e-11e9-8a97-a2143a903a00.png)

[Screen Shot 2019-10-10 at 9.14.58 am.png.zip](https://github.com/awslabs/video-on-demand-on-aws/files/3709614/Screen.Shot.2019-10-10.at.9.14.58.am.png.zip)

 correctly.



{
  "guid": "5c040d76-6da7-486f-8583-fe7971dd65a3",
  "workflowStatus": "Error",
  "workflowErrorAt": "Encoding",
  "errorMessage": "The properties of your input file, combined with your job settings, aren't compatible with accelerated transcoding: [There is no initial timecode available in this input: [1]. Therefore, you can't use accelerated transcoding on this input unless the input timecode configuration source (Settings > Inputs[1] > Source) is set to Start at 0 (ZEROBASED). Edit your job to set this value to Start at 0 (ZEROBASED), or disable accelerated transcoding.]",
  "errorDetails": "https://console.aws.amazon.com/mediaconvert/home?region=ap-southeast-2#/jobs/summary/1570658184924-j5rlde"
}
{
  "guid": "0d054608-3a54-4fef-98cb-c2676f083748",
  "workflowStatus": "Error",
  "workflowErrorAt": "Encoding",
  "errorMessage": "Unknown error",
  "errorDetails": "https://console.aws.amazon.com/mediaconvert/home?region=ap-southeast-2#/jobs/summary/1570658013068-iziqkz"
}

**Comment by dscpinheiro** [comment]
> Initially I thougth the same and created the attached template, but when the job runs it does not use the chosen queue but the default one.
> 
> Can that be a MP issue or solution issue?

For this problem I'm afraid I won't be able to help you (since it seems to be related to MediaConvert and not part of the VOD solution). The weird thing is that the job correctly uses the other template settings (such as status update interval and priority).

What I recommend is contacting AWS Support and providing them with both files you attached to this issue (the template and the job details).

**Comment by ffiore1** [comment]
will do.
by the way, the solution does not manage the status update interval and priority.
I made them work only setting them in the template, as you also advise.

**Comment by ffiore1** [comment]
@dscpinheiro is the release 5.0 managing additional MC custom templates now? 

I do not see that in the release notes, so just wondering it.

**Comment by dscpinheiro** [comment]
Yes, the fix I mentioned previously (https://github.com/awslabs/video-on-demand-on-aws/issues/38#issuecomment-539044144) is included.
