### ISSUE TITLE
Want to create different buckets in the end

### ISSUE THREAD

**Issue by tapanjo92** [awslabs/video-on-demand-on-aws#39]
I want to implement a lambda function, where every video converted, will automatically create a new bucket with tag and if the video is from the same customer that video will go into that bucket

**Comment by dscpinheiro** [comment]
Hi @tapanjo92,

We don't plan on adding this functionality to the solution, but you can customize yourself if you want to. You'd have to change the [_encode function_](https://github.com/awslabs/video-on-demand-on-aws/blob/master/source/encode/index.js#L30) so that the file is saved to the desired bucket (instead of _destBucket_).

It's also important to be aware of [S3 limits](https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html): You can only create up to 100 buckets by default, and this value can only be increased to a maximum of 1,000. If you have lots of customers, this might not be the best approach. An alternative is to use a single bucket, but use sub-folders for each customer.

**Comment by tapanjo92** [comment]
Hi @dscpinheiro ,

Yes i figured that, given we have different customers, so we need to create lambda function for each of them in the encode? with their name?

**Comment by dscpinheiro** [comment]
No, you should be able to use only one encode function.

What you can do is: whenever you upload a new file to S3, specify the _destBucket_ property to point to that customer's bucket (important to remember this is only possible if the workflow trigger is set to _MetadataFile_).

**Comment by tapanjo92** [comment]
@dscpinheiro ,
can i get any sample code help if possible?

thank you

**Comment by dscpinheiro** [comment]
We don't have any sample code, but here's what you could do:

For customer A, you'd upload this metadata file:
```json
{
  "srcVideo": "cust-A-video.mp4",
  "destBucket": "cust-A-bucket"
}
```

Whereas for customer B, the metadata file would look like this:
```json
{
  "srcVideo": "cust-B-video.mp4",
  "destBucket": "cust-B-bucket"
}
```

This should be enough for the workflow to put the files in different buckets.
Again, as I stated in a previous comment (https://github.com/awslabs/video-on-demand-on-aws/issues/39#issuecomment-542208256), this might work, but you might run into some issues regarding S3 limits.

**Comment by tapanjo92** [comment]
@dscpinheiro 
Thank you for your recommendation. We decided to go with creating different folders instead of buckets.
Now each time you put video through Media convert, the folders are automatically created. So can we just edit the lambda function?

**Comment by dscpinheiro** [comment]
Hi @tapanjo92,

Yes, by default the encode function uses the execution id as the destination folder, but you should be able to change it so that it uses a custom folder instead.

**Comment by tapanjo92** [comment]
@dscpinheiro 
I tried editing the encode function, but I am getting a problem when I am trying to customise it because it has been referenced everywhere, can I get a more specific answer on which area I should edit the function. As u mentioned earlier on line 30, but I am not able to edit that as it is giving me an error.

**Comment by dscpinheiro** [comment]
> @dscpinheiro
> I tried editing the encode function, but I am getting a problem when I am trying to customise it because it has been referenced everywhere, can I get a more specific answer on which area I should edit the function. As u mentioned earlier on line 30, but I am not able to edit that as it is giving me an error.

What error are you getting?

**Comment by dscpinheiro** [comment]
No worries, sorry for the confusion on my part.

Here is what I'd do (and please let me know if any of these don't make sense):

1. Launch the template with the _WorkflowTrigger_ parameter set to _MetadataFile_
2. Update [line 30](https://github.com/awslabs/video-on-demand-on-aws/blob/master/source/encode/index.js#L30) on the encode function from this:

```javascript
let outputPath = 's3://' + event.destBucket + '/' + event.guid;
```

To this:

```javascript
let outputPath = `s3://${event.destBucket}/${event.subFolder}/${event.guid}`;
```

3. Whenever uploading a file, populate the _subFolder_ property according to the customer. For instance:
```json
{
  "srcVideo": "cust-A-video.mp4",
  "subFolder": "cust-A-folder"
}
```

**Comment by tapanjo92** [comment]
@dscpinheiro Thak you for the help,
so we have an api call, wherein customer develop theor video file, but there is no way for the metadata to be embedded.

**Comment by dscpinheiro** [comment]
@tapanjo92,

It should still be possible without the metadata, it will just be slightly more complicated.

What I was thinking is, whenever a video file is uploaded to S3 via your API, you add some tags to the object so that the customer can be identified.

Then, in the encode function, instead of looking for that _subFolder_ property, you check the tags to update the destination path.

Would that work?

**Comment by tapanjo92** [comment]
Yes that should work!
what can I edit in the encode function?

**Comment by dscpinheiro** [comment]
Same place as before, when _outputPath_ is populated.
The _event_ variable has the S3 bucket and key, so you should be able to use the SDK to get the object tags.

**Comment by tapanjo92** [comment]
@dscpinheiro 
Thank you so much. I will work this weekend.
I will get back to you with more questions if any.

**Comment by tapanjo92** [comment]
Hi @dscpinheiro ,

It was working fine, but when I created a new CFN template and edited the lambda code, I am getting this error whenever I insert .json file in the S3 bucket.
![44](https://user-images.githubusercontent.com/49943773/68563734-a0f75c00-04a2-11ea-86c2-6b369f1c4c69.png)

thank you

**Comment by dscpinheiro** [comment]
Which Lambda function is that message coming from? Could you post the JSON file you're using?

**Comment by tapanjo92** [comment]
Looks like it's coming from lambda function 'error-handler'
The json file used was
`{
    "srcVideo": "animal.mp4",
    "subFolder": "animal"
}`

**Comment by dscpinheiro** [comment]
The error-handler function is only invoked when another function fails.
Could you check the state machines? The failed execution should show up there, and you'll be able to see where the error happened.

**Comment by tapanjo92** [comment]
hi @dscpinheiro  ,
looks like error came from 'input validate' - lambda function.
I have attached some screenshots.
![52](https://user-images.githubusercontent.com/49943773/68583089-702e1b80-04d0-11ea-90c1-06d80ec890a6.png)
![50](https://user-images.githubusercontent.com/49943773/68583091-702e1b80-04d0-11ea-9d3b-f2534ac89a67.png)
![51](https://user-images.githubusercontent.com/49943773/68583092-70c6b200-04d0-11ea-9b67-2e444fa16f8d.png)

**Comment by tapanjo92** [comment]
@dscpinheiro 
Also, I tried to create CFN this template given in this github
[CFN template for vod-on-demand](https://github.com/awslabs/video-on-demand-on-aws/blob/master/deployment/video-on-demand-on-aws.yaml)
I am getting this error again and again while creating it.
![53](https://user-images.githubusercontent.com/49943773/68588353-665ee500-04dd-11ea-9c3a-38b8ffa34e6d.png)

**Comment by dscpinheiro** [comment]
The template on GitHub is not meant to be used directly. You have to follow the steps in https://github.com/awslabs/video-on-demand-on-aws#creating-a-custom-build if you want to customize the solution.

For the previous comment, can you confirm that these two environment variables (_FrameCapture_ and _ArchiveSource_) are defined for the input-validate function?

<img width="957" alt="Screen Shot 2019-11-11 at 7 57 33 AM" src="https://user-images.githubusercontent.com/3842788/68589071-0161ab80-0459-11ea-8f00-8008da14277c.png">

With the metadata option, they can be overwritten, but default values must be set.

**Comment by tapanjo92** [comment]
Yes FrameCapture and ArchiveSource are defined and been set to false.
![54](https://user-images.githubusercontent.com/49943773/68589325-b9d23280-04df-11ea-8091-9d82c79ea748.png)

**Comment by tapanjo92** [comment]
@dscpinheiro 
As of now the template is working. I will get back to you if I get some more data after research with regards to why I was getting an error.
Thank You very much for helping me

**Comment by dscpinheiro** [comment]
Ok, thanks for the update.

If you do figure out what the problem was, please let us know. If it's an issue with the solution, we want to fix it for other customers as well.

**Comment by tapanjo92** [comment]
@dscpinheiro 
As AWS is ending support for Node.js 8.x
Any update on when CFN template will be updated with node.js 10.x?

**Comment by dscpinheiro** [comment]
We'll release a new version of the solution before Node 8 reaches its End of Life, and that version will update the runtime to Node 10.

**Comment by tapanjo92** [comment]
hi @dscpinheiro ,

Is there a way in which I can get the total length of the video in sns notification from dynamodb?
![lam-outputvalidate](https://user-images.githubusercontent.com/49943773/69103193-ddd1dd00-0ab8-11ea-9ecd-868f15a1ba6a.png)
![sns](https://user-images.githubusercontent.com/49943773/69103196-de6a7380-0ab8-11ea-9cb6-1d2e91c5d24e.png)
![dynamo](https://user-images.githubusercontent.com/49943773/69103198-de6a7380-0ab8-11ea-8220-00fa821d54f7.png)

**Comment by dscpinheiro** [comment]
Hi @tapanjo92,

Yes, there is. You could use the _encodingOutput_, as you showed on the screenshot, but an easier option is to use the mediainfo output.

The _srcMediaInfo_ property on Dynamo should have the duration of the video.

**Comment by tapanjo92** [comment]
but how can I get srcMediainfo's output on sns?

**Comment by tapanjo92** [comment]
Hi @dscpinheiro 
but how can I get srcMediainfo's output on sns?

**Comment by dscpinheiro** [comment]
Here's an example for the profiler function: https://github.com/awslabs/video-on-demand-on-aws/blob/16bef0e010d0cd340546b65af0e0a0723c7b50e3/source/profiler/index.js#L40-L42

This property is removed in the sns function, but you can modify it so that the duration is included: https://github.com/awslabs/video-on-demand-on-aws/blob/16bef0e010d0cd340546b65af0e0a0723c7b50e3/source/sns-notification/index.js#L34
