### ISSUE TITLE
Trouble deploying the solution

### ISSUE THREAD

**Issue by rajcheval** [awslabs/video-on-demand-on-aws#43]
I downloaded the entire repo and checked it into AWS CodeCommit. We will make code changes for my initial attempt was to follow the instructions to deploy the solution.
I had an existing S3 bucket. We use us-east-1 region
 
./build-s3-dist.sh my-bucket 1.00
aws s3 sync dist/ s3://my-bucket/video-on-demand-on-aws/1.00/
It did upload the tempate and zip files to the s3 bucket.
I want to AWS Console Cloud Formation and referred to the template in S3 bucket.

My stack failed to deploy.
CustomResource failed to provision.
Error was: Error occurred while GetObject. S3 Error Code: NoSuchBucket. S3 Error Message: The specified bucket does not exist (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 4efa5ade-4a90-4dcd-b08d-c4416408da51)

#Custom Resource Lambda Function
  CustomResource:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-custom-resource
      Description: Used to deploy Step Functions and additional, cloudfront s3 and sns Configuration
      Handler: index.handler
      Role: !GetAtt CustomResourceRole.Arn
      Code:
        S3Bucket: !Join ["-", [!FindInMap ["SourceCode", "General", "S3Bucket"], Ref: "AWS::Region"]]
        S3Key: !Join ["/", [!FindInMap ["SourceCode", "General", "KeyPrefix"],  "custom-resource.zip"]]
      Runtime:  nodejs8.10
      Timeout: 180

I examined the template file and it did have correct bucket name and path.
I did this from Mac not windows PC.

When I directly refer to the template in AWS s3 bucket the deployment is successful.
This issue is similar to https://github.com/awslabs/live-stream-on-aws/issues/5

Let me know if you have a suggestion for me.

**Comment by dscpinheiro** [comment]
Hi @rajcheval,

Sorry for the inconvenience. Unfortunately the instructions on the README file are a bit confusing at the moment, but in the next release of the solution we'll update them to be more clear.

The bucket must have the region name where you plan to launch the template as a suffix (for instance, _my-bucket-us-east-1_). Once the bucket is created, you should invoke the _build-s3_ script passing the bucket name **without** the suffix:

```console
./build-s3-dist.sh my-bucket 1.00
```

After the script finishes, you should copy the files to S3, however this command requires the **full bucket name**:

```console
aws s3 sync dist/ s3://my-bucket-us-east-1/video-on-demand-on-aws/1.00/
```

Please let us know if that fixes your problem.

**Comment by rajcheval** [comment]
@dscpinheiro Thank you for your quick response. It resolved my issue.
