### ISSUE TITLE
Add support for Audio Only files

### ISSUE THREAD

**Issue by aloussayef** [awslabs/video-on-demand-on-aws#47]
Hi, 

I have a use case where i need to use the workflow to transcode Videos and Audio only files.
Right now the Profiler function applies the MediaConvert template based on the resolution gathered from MediaInfo.
I know that i can overwrite the template by uploading a manifest file along with the media. However it would be nice to implement a logic that can process Audio Only files and detect the template to use once uploaded to the source bucket. 

Can you please give me some thoughts/recommendation on how this can be accomplished?
I want to keep the Video template profiling based on Height but i want to add support for audio only .wav files 

Thanks, 
-Kader

**Comment by dscpinheiro** [comment]
Hi @aloussayef,

There was another issue with a similar problem (processing videos with no audio) https://github.com/awslabs/video-on-demand-on-aws/issues/45, and as I mentioned there https://github.com/awslabs/video-on-demand-on-aws/issues/45#issuecomment-558183764, this is something that's on the backlog for future releases of the solution. 

I'll make sure to include your use case of wav files as well.

**Comment by tomnight** [comment]
Request added to our backlog, closing thread
