### ISSUE TITLE
PLEASE PUT HUGE WARNING ON HOW EXPENSIVE RUNNING THIS IS!!!! I'M PRAYING THE BILLING DEPARTMENT WAIVES MY $8000 CHARGE

### ISSUE THREAD

**Issue by Kurry** [awslabs/video-on-demand-on-aws#48]
I just checked my AWS balance after running this for just 800 videos. OMFG.
![aws-spend](https://user-images.githubusercontent.com/857247/70757908-3d658600-1d0f-11ea-922c-fb919c33d91d.PNG)

**Comment by Kurry** [comment]
40 cents/minute to convert 4k video, this is insane!

![billing-details](https://user-images.githubusercontent.com/857247/70759709-48bbb000-1d15-11ea-9720-03d35a14e8d3.PNG)

**Comment by dscpinheiro** [comment]
Hi @Kurry,

We are really sorry for the bad experience and thank you for the feedback and bringing this to our attention. Both this repository and the documentation on the solution home page are not very clear about costs, and this is something we will review. If you would like to discuss the bill issue you have raised please reach out to our support team who will be happy to assist you (https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/billing-get-answers.html). You can reference this issue on the support ticket.

The best way to estimate how much running the solution costs is to look at the examples on the MediaConvert pricing page (https://aws.amazon.com/mediaconvert/pricing/), which is the main cost component of the solution.

The encoding templates used by the solution are configured to give the best quality for the size of the media outputs but there are a number of options available to you to reduce the overall cost. For reference:
- Use Reserved Pricing in MediaConvert (https://aws.amazon.com/blogs/media/reserved-pricing-in-aws-elemental-mediaconvert-part-1-intro-and-how-to-use-it/) or switch to the basic tier. The solution is configured to use the Professional Tier by default for some codecs.
- Use custom encoding templates (https://github.com/awslabs/video-on-demand-on-aws#encoding-templates). The default media outputs include 4 formats and 7 bitrate versions including HLS, DASH, CMAF and MSS. If not all of these formats are required then you can reduce the cost of the encoding by removing the presets you don’t need.
- If you are not using the latest version (v5), which leverages MediaPackage VOD (https://docs.aws.amazon.com/mediapackage/latest/ug/vod-content.html), evaluate if that is possible. With this option the encoding cost will be greatly reduced as the solution will create a single set of HLS content in S3. MediaPackage VOD is configured to serve the other formats using just-in-time packaging based on demand.

If you haven't done so, we would also recommend either:
- Creating a budget in Cost Explorer (https://aws.amazon.com/aws-cost-management/aws-budgets/); or
- Creating a Billing Alarm in CloudWatch (https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/monitor_estimated_charges_with_cloudwatch.html)

Again, we apologize for the bad experience.

**Comment by Kurry** [comment]
@dscpinheiro Thank you for the response, I did reach out to billing yesterday and they said they would see what they could do. Thanks for the code and great project overall! I wish it did have a pre-built in template to support 5k, 4k video, because you'd think people would want the at least the same resolution they put in. The one thing I am having trouble with is embedding it into a web page to support both Safari and Chrome. If you could create a sample html website to display all the endpoints, that would be helpful. I do see an issue where the HLS index file doesn't load the movie automatically. It launches in a new browser, but it just plays audio, I have to refresh the page to see the whole video. Any ideas why?

**Comment by dscpinheiro** [comment]
Hi @Kurry,

I'm glad you like the solution!

For a future version, we are looking at adding a demo UI so that you can test the outputs of the workflow.
We'll also look at the latest MediaConvert features, such as 8K (https://aws.amazon.com/about-aws/whats-new/2019/11/8k-resolution-encoding-now-available-with-aws-elemental-media-convert/).

**Comment by Kurry** [comment]
@dscpinheiro I had a happy ending! Luckily the AWS billing department approved a billing adjustment of $7,745.46. Now I have a great library of streaming videos for free!

With respect to the project, a couple feature requests:

1) Some sort of pre-processing to check to see if the file will be successfully converted. I had a couple of jobs that failed because of an audio issue and was still charged for the job.  If you're converting a 60 or 120 minute video, that could be a $23 - $45 mistake.

2) A default index to allow for easier sorting/paging within dynamo db.

3) Use machine learning to pick a better thumbnail image. I had some thumbnails there were just blank or just a black screen, so either use a key frame or some heuristic to pick the image.

4) A REST API using AWS Lambda which uses a template to generate the sample website.

**Comment by dscpinheiro** [comment]
Hi @Kurry,

I'm glad you were able to solve the billing issue.
I've also added the features to our backlog.

**Comment by georgebearden** [comment]
Closing this issue for now, but please let us know if you need anything else.
