### ISSUE TITLE
I am using the video-on-demand template but I need a predictable output folder that will be served on CloudFront.

### ISSUE THREAD

**Issue by marciomarinho** [awslabs/video-on-demand-on-aws#5]
Hi,

I am building an learning website, and using the Video on Demand solution to store and process the videos : https://aws.amazon.com/answers/media-entertainment/video-on-demand-on-aws/

My problem is I'm using Wordpress and my users will upload the file to the source S3 bucket, and the Wordpress plugin is expecting to be able to map the source file to the cloudfront root folder, e.g:

Source File name : abcdef.mp4
Destination Address : xxxxx.cloudfront.net/hls/abcdef.mp4 ( or some known folder pattern )

The cloudformation solution generates a uuid folder for each file and will drop the file inside this random and unknown folder on the destination bucket. Is there a way to configure it to always have a predictable destination folder, so I can avoid having to write a lot of custom code to find the file ?

Base Use Case : 
1) Drop a file in the source folder
2) AWS Video on demand will process the file
3) I can refer to the target file on CloudFront without having to code my application to discover the file's destination.

**Comment by adamdabbracci** [comment]
I had this same issue but using a custom built CMS. I ended up setting the source file name to a UID that I stored and referenced. But +1 for the feature... I may work on this when I get a chance.

**Comment by marciomarinho** [comment]
I started doing exactly that, but stopped as I think it should be a configuration effort and not a coding one.

**Comment by adamdabbracci** [comment]
I agree. There is a UID (the primary key of the Dtano table) that’s generated when the first Lambda runs so I’m sure a value could be passed in as a config.

**Comment by marciomarinho** [comment]
Yeah, I saw that as well. But my problem is not only that... if you look at the destination folder, it is a random UUID which we will only know at the very end. If the process was synchronous and we got a target URL after posting the file ( through a lambda or any other service ) it would also work. I thought on doing that as well, but I would spend too much time.

**Comment by rromanchuk** [comment]
Curious how you guys implemented this end to end.  For a simple scenario, let's say we have an object `Post` that persistently stored in a traditional database. This object is responsible for returning the asset urls.  After the user uploads a video to the source bucket, a traditional REST POST is sent for the creation of this `Post` object. In the past, knowing the s3 `keypath` and filename was enough information to know where final remote URLs are located, even if the outputs may not have completed processing in a traditional elastic transcoder pipeline. 

Are you guys listening for what i assume is an SNS completion push, and using the source file name to look up the dynamodb output locations, where i could then update my record? Did you add a global secondary index to `srcFile`?  There's probably a much cleaner implementation but i'm trapped in my last paradigm. I also noticed thumbnail information is missing form dynamo. This is a big cloudformation stack so i'm still reviewing the stack.

**Comment by rromanchuk** [comment]
Ahh i see, there's the completion SNS

Start notification

```json
{
  "StartTime": "2018-09-25 23:13.1",
  "Source Video": "89BC76F0-6126-4226-8026-7BFEC8CC626F.mp4"
}
```

Finish notification
```json
{
  "guid": "75f17e89-c647-44a4-a3e6-f1eb3f441af0",
  "srcVideo": "89BC76F0-6126-4226-8026-7BFEC8CC626F.mp4",
  "hlsUrl": "https://redacted/75f17e89-c647-44a4-a3e6-f1eb3f441af0/hls/89BC76F0-6126-4226-8026-7BFEC8CC626F.m3u8",
  "dashUrl": "https://redacted/75f17e89-c647-44a4-a3e6-f1eb3f441af0/dash/89BC76F0-6126-4226-8026-7BFEC8CC626F.mpd",
  "mp4Outputs": [
    "75f17e89-c647-44a4-a3e6-f1eb3f441af0/mp4/89BC76F0-6126-4226-8026-7BFEC8CC626F_720p.mp4",
    "75f17e89-c647-44a4-a3e6-f1eb3f441af0/mp4/89BC76F0-6126-4226-8026-7BFEC8CC626F_1080p.mp4"
  ]
}
```

Makes sense that #13 needs to be added to this response as well

**Comment by rromanchuk** [comment]
BTW, my final approach ✈️ to this was to create another subscription  (webhook) to the sns topic, on success i retrieve VOD information from dynamodb and update my own object graph with the information required. Also added a GSI on srcVideo in order to query from my own FK. I also heavily modified what i' m saving to dynamo
