### ISSUE TITLE
How often will Node.js updates cause breaking changes?

### ISSUE THREAD

**Issue by mike-source** [awslabs/video-on-demand-on-aws#51]
**Disclaimer: I am a new user and also new to AWS in general so forgive if I've misunderstood anything.**

I have been doing some testing and trying to build a video upload & streaming website using the Video On Demand template and I recently started receiving the following automated emails:

> Subject: AWS Lambda: Node.js 8.10 is EOL, please migrate your functions to a newer runtime version
>
> Hello,
> 
> We are contacting you as we have identified that your AWS Account currently has one or more Lambda functions using Node.js 8.10, which will reach its EOL at the end of 2019.
> 
> What’s happening?
> 
> The Node community has decided to end support for Node.js 8.x on December 31, 2019 [1]. From this date forward, Node.js 8.x will stop receiving bug fixes, security updates, and/or performance improvements. To ensure that your new and existing functions run on a supported and secure runtime, language runtimes that have reached their EOL are deprecated in AWS [2].
> 
> For Node.js 8.x, there will be 2 stages to the runtime deprecation process:
> 
> 1. Disable Function Create – Beginning January 6, 2020, customers will no longer be able to create functions using Node.js 8.10
> 
> 2. Disable Function Update – Beginning February 3, 2020, customers will no longer be able to update functions using Node.js 8.10
> 
> After this period, both function creation and updates will be disabled permanently. However, existing Node 8.x functions will still be available to process invocation events.
> 
> What do I need to do?
> 
> We encourage you to update all of your Node.js 8.10 functions to the newer available runtime version, Node.js 10.x[3] or Node.js 12.x[4]. You should test your functions for compatibility with either the Node.js 10.x or Node.js 12.x language version before applying changes to your production functions.
> 
> What if I have issues/What if I need help?
> 
> Please contact us through AWS Support [5] or the AWS Developer Forums [6] should you have any questions or concerns.
> 
> [1] https://github.com/nodejs/Release
> [2] https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html
> [3] https://aws.amazon.com/about-aws/whats-new/2019/05/aws_lambda_adds_support_for_node_js_v10/
> [4] https://aws.amazon.com/about-aws/whats-new/2019/11/aws-lambda-supports-node-js-12/
> [5] https://aws.amazon.com/support
> [6] https://forums.aws.amazon.com/forum.jspa?forumID=186
> 
> Sincerely,
> Amazon Web Services

The video on demand solution was 'sold' to us by an AWS sales rep as a more or less set and forget solution, it took me some time and reading and going back and forth with your support staff to establish that this had something to do with the lambda functions that are part of the VOD workflow. The pdf documentation had been updated last month to include the following notice (easily missed in my opinion):

> Solution Updates:
> Video on Demand on AWS version 5.0 features MediaPackage functionality, and uses the most up-to-date Node.js runtime. Version 4.2 uses the Node.js 8.10 runtime, which reaches end-of-life on December 31, 2019. In January, AWS Lambda will block the create operation and, in February, Lambda will block the update operation. For more information, see Runtime Support Policy in the AWS Lambda Developer Guide.
> 
> To continue using this solution with the latest features and improvements, you must deploy version 5.0 as a new stack. For customers who do not want to use the new functionality, you can update your existing stack to version 4.3. Version 4.3 keeps the same functionality as version 4.2 but uses the most up-to-date runtimes. You can find both versions in the solution’s GitHub repository. You can also download the version 4.3 template.
> 

**(please forgive all the copy pastes, I'm trying to include as much info as possible in one place just for the benefit of anyone else in a similar boat to me!)**

My concern was that deploying a new stack would involve losing the crucial data in the DynamoDB table associated to the stack (on a live version of my site this could be hundreds of videos+metadata), and whether or not the contents of the destination S3 buckets would be somehow orphaned. I don't think it's very clear from your documentation how to perform an update to version 5.0 on a live site or project that depends on this stack and what is affected.

When I asked support staff for some guidance on this I was told:

> - Create a new stack with version 5.0
> - Update this stack by deleting/removing dynamodb::table resource from the template
> - Once the above update is completed successfully, perform a second update on this stack to import the dynambodb table which you were using into this stack.

This might make sense to someone with a bit more AWS experience but for a relative newbie like me it didn't fully address my concerns about losing my current data.

When I enquired further I was given instructions for updating from version 4.2 to version 4.3 instead, but I don't see that as a future proof solution at all, **how long until 4.3 is obsoleted due to use of some deprecated/EOL code?**

I'll include the response to the rest of my questions from the support staff who also recommended I post here for more info. Again, apologies for so much reading, but this is useful info for anyone stuck in my position.

> _Below answers are not relevant when updating from 4.2 to 4.3. These are concerned to version 5.0 (as creating a new stack is the only option for version 5.0) and you can completely ignore this information if you would like to._
> 
> ===========
> 
> Q1: When you say create a new stack do you mean to run  "Launch Solution" again from the PDF like I did last time?
> 
> _Yes, the pdf that you were referring to [2] is now updated and "Launch solution" will now launch a new stack with version 5.0. This is a quick solution. But there are other methods to upload a template to cloudformation [4]._
> 
> Q2: How do I delete/remove the dynamodb::table resource from "the template"? Which "template" are you referring to here, is the CloudFormation "stack" a template?
> 
> _Here is a documentation[5] which details steps to modify a cloudformation template. Once you get to "step 3: Modify the template", search for AWS::DynamoDB::Table resource and remove this resource section from the template file._
> 
> Q3: How do I perform updates on "stacks", and how would I perform an update which imports a dynamodb table?
> 
> _To import dynamodb table, please see this documentation[6]. And, here is a documentation[3] that describes steps to perform updates on a stack._
> 
> Q4: Do I need to export my current dynamoDB table and if so how do I do that? (and also reimport).
> 
> _If you follow documentation [6] it is not necessary to export dynamodb resource. Importing itself helps._
> 
> Q5: Also I need to know how often there will be breaking changes like this because my concern is that if this is something that can happen often then I'm not sure I can trust what I'm using. Will there be potential of losing data every time I attempt to update the stack/workflow/cloudformation/template? (I'm still not clear what the correct terminology is here).
> 
> _I would suggest moving from version 4.2 to 4.3 which is not a breaking change as this is not replacing the resources. As Premium Support members do not have an idea of future updates, I would recommend you to try creating a github issue under VideoOnDemand GitHub issues [7]. One of our soultions architect will address your concern._
> 
> Q6: will all of the security credentials and IAM roles and Cognito Identity pools etc. need to be redone as well?
> 
> _These resources need not be redone._
> 
> ======
> 
> I hope this information helps you. Please do not hesitate to reach back to me if you have further questions or concerns. I will be glad to assist you further.
> 
> Thank you and have a great rest of the day!
> 
> 
> References:
> 
> 1. GitHub ChangeLog: https://github.com/awslabs/video-on-demand-on-aws/blob/master/CHANGELOG.md
> 2. VideoOnDemand: https://s3.amazonaws.com/solutions-reference/video-on-demand-on-aws/latest/video-on-demand-on-aws.pdf
> 3. Updating stack: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-direct.html 
> 4. Selecting a template: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-using-console-create-stack-template.html
> 5. Modifying a template: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-get-template.html
> 6. Importing resources into stack: https://aws.amazon.com/blogs/aws/new-import-existing-resources-into-a-cloudformation-stack/
> 7. github issues page: https://github.com/awslabs/video-on-demand-on-aws/issues

**Can anyone shed some light on whether version 5.0 is something I can rely on going forward, or should I expect to have to do the above steps relatively often? I imagine a lot of users would need to know this so that they can budget accordingly for maintenance & manual updating costs. Is there any way to automate updating the stack? Is that wise? How would you suggest maintaining this stack on a production environment?**

**Comment by dscpinheiro** [comment]
Hi @mike-source,

Thanks a lot for the feedback. You're correct that the documentation could be improved (at the moment, there's a bit of an overlap between the README and the implementation guide), and this is something we will review for future releases.
As I wrote on https://github.com/awslabs/video-on-demand-on-aws/issues/37#issuecomment-556460396, we are planning on writing a blog post, and one of the things we will mention is moving data from the previous version.

We don't plan on adding any updates to v4.3 (this version was released specifically to address the Node 8 runtime reaching its EOL). On the other hand, we are going to keep adding features and fixing any bugs to v5, and you should be able to rely on it moving forward without having to go through the series of steps you listed (we've made improvements to guarantee a cleaner update path).

If you have any more questions, please let us know.

**Comment by mike-source** [comment]
Well, as my project is currently in development, v4.3 seems useless to me. I would not want to deploy a production version of my project locked in to a version that will be receiving no bug fixes.

I'm in the middle of a project and working to a deadline, what would you recommend:

Attempt to upgrade to v4.3 for now, allowing me to continue development after December 31st 2019 on my frontend, and wait for these better instructions for the v5 upgrade?

Will going from v4.3 to v5.0 be quite painless?

Also can you give some idea when the blog post or better documentation will be available, as I need to pass on info about any delays to my client and colleagues.

I would certainly make that a priority! This is not a fun position to be in at my end!

Thanks for the response though and I hope this gets addressed soon as the stack itself has been working great for me up until now.

**Comment by mike-source** [comment]
I don't appear to be able to follow the steps for updating to v5.0 provided by the AWS support staff above by the way! - I get as far as "step 3: Modify the template" I search for the "AWS::DynamoDB::Table" resource and try to remove this from the template by removing lines 801-831 from the template in template designer.

When I do that step I get the following error:

"Template contains errors.: Template format error: Unresolved resource dependencies [DynamoDBTable] in the Resources block of the template"

I'm then unable to proceed with the instructions. I assume from this error the issue is you can't just remove the DDB Table because there are other parts of the stack that expect it to be there? or perhaps I've missed something obvious!

I think they may also be overlooking the fact there are source and destination S3 buckets attached to the workflow as well, these contain files which would need to be migrated/attached to the new 5.0 stack. 

Does this not also need to be done by modifying the template?

Sorry for bombarding you with questions!

**Comment by dscpinheiro** [comment]
No need to apologize for that, we want as much feedback as possible.

We won't be able to release the blog post this year, so what we'd recommend is using v4.3 for the moment (so that you can update your functions - if needed - after January 1st).

Version 5 is not backwards compatible with v4.3 (it won't be possible to just update the existing stack), but in the blog post we'll address the points you mentioned (such as moving data between DynamoDB tables).

**Comment by georgebearden** [comment]
Hi @mike-source - Closing this issue for now but please let us know if you need additional assistance.
