### ISSUE TITLE
Possibly, add in the roadmap MediaPackage endpoints as a possible input for the VOD solution

### ISSUE THREAD

**Issue by ffiore1** [awslabs/video-on-demand-on-aws#53]
This would add Live2VOD capability to the solution with a different cost model (CDN costs vs MediaPackage costs) compared to the out of the box capability in MediaPackage (harvest job)

**Comment by tomnight** [comment]
Thanks for the feedback, Live2Vod is a subject area we would like to look into and we will add the request to our roadmap.

**Comment by ffiore1** [comment]
howdy @tomnight , just wondering if you have any indicative/tentative eta for that? 

in the meanwhile, which would be your advice/suggested approach to ingest in MediaConvert chunks and relaed manifests already present in a S3 bucket? SMIL? any advice would be appreciated  @dscpinheiro @here

**Comment by tomnight** [comment]
Request has been add tour backlog, closing old issue
