### ISSUE TITLE
MOV files not supported?

### ISSUE THREAD

**Issue by khazaddoom** [awslabs/video-on-demand-on-aws#54]
Hi, I see that the whole suite works well when i place a .MP4 file to the Source Bucket. Roughly around 4 mins later i can see the 3 different types of Streamable CDN links.
However when I upload a .MOV file(i recorded a 1 minute video in my iPhone 6s(default settings) which is around 120MB, i dont see the workflow getting triggered at all! There is notification to my email.
Where can i find the Input video file types that are supported?

**Comment by khazaddoom** [comment]
I digged a bit deeper to find out from the documentation that "it is not enough to place the video file alone but also a metadata file in the specific format!" Is this correct?

But this aws forum [post](https://forums.aws.amazon.com/thread.jspa?threadID=285276&tstart=0) says .MOV is already supported and I should in fact find a lambda on the source bucket Events configured already! Rightly so i did find it but still when i place the .MOV file i dont see the workflow triggering.

going deeper now ...

**Comment by dscpinheiro** [comment]
The list of supported formats is: mpg, mp4, m4v, mov, and m2ts. However, the extensions are case sensitive, so _video.mov_ will start the workflow, but _video.MOV_ will not.

For the second question, when you launch the template, there's a _WorkflowTrigger_ parameter, and you can select one of these values:
- _VideoFile_: With this option, all you have to do is upload a file to the S3 bucket.
- _MetadataFile_: With this option, in addition to uploading the video file, you also have to upload a json file with the workflow details. The details are explained on the README file (https://github.com/awslabs/video-on-demand-on-aws#source-metadata-option)

You only have to upload a metadata file if you selected _MetadataFile_ when creating the stack.

**Comment by khazaddoom** [comment]
> The list of supported formats is: mpg, mp4, m4v, mov, and m2ts. However, the extensions are case sensitive, so _video.mov_ will start the workflow, but _video.MOV_ will not.
> 
> For the second question, when you launch the template, there's a _WorkflowTrigger_ parameter, and you can select one of these values:
> 
> * _VideoFile_: With this option, all you have to do is upload a file to the S3 bucket.
> * _MetadataFile_: With this option, in addition to uploading the video file, you also have to upload a json file with the workflow details. The details are explained on the README file (https://github.com/awslabs/video-on-demand-on-aws#source-metadata-option)
> 
> You only have to upload a metadata file if you selected _MetadataFile_ when creating the stack.

Awesome! Thanks these points helped a lot.
