### ISSUE TITLE
Missing required key 'Name' in params (VOD encode)

### ISSUE THREAD

**Issue by sadikay** [awslabs/video-on-demand-on-aws#55]
I pulled the latest version of the template(v5.0.0) and I have customized the output options (removed low quality options) and deployed the template successfully. But after uploading a video to source bucket getting this error in `encode` lambda function: 

```
"errorType": "MissingRequiredParameter",
 "errorMessage": "Missing required key 'Name' in params",
 "code": "MissingRequiredParameter",
```
just checked the code in `encode/index.js` the code expecting the request event to has `jobTemplate` parameter. For example:
```
182: let tmpl = await mediaconvert.getJobTemplate({ Name: event.jobTemplate }).promise();
```
The lambda function printing the event variables like below before failing:

```
{
    "guid": "b26b7974-5c55-47c6-9dba-fa1bf1cf5e28",
    "destBucket": "video-stream-destination-njqsuvm4k2q1",
    "workflowStatus": "Ingest",
    "frameCapture": true,
    "jobTemplate_2160p": "video-stream_Ott_2160p_Avc_Aac_16x9_qvbr",
    "jobTemplate_720p": "video-stream_Ott_720p_Avc_Aac_16x9_qvbr",
    "jobTemplate_1080p": "video-stream_Ott_1080p_Avc_Aac_16x9_qvbr",
    "workflowName": "video-stream",
    "workflowTrigger": "Video",
    ....
```

as you see there is no `jobTemplate` parameter which the function expecting. Did I miss something or this is an issue ?

**Comment by dscpinheiro** [comment]
Hi @sadikay,

There's a function in the workflow that selects a job template based on the encoding profile: https://github.com/awslabs/video-on-demand-on-aws/blob/97049f1d9a551f7dd357e1eedc3f075d11fa67ce/source/profiler/index.js#L74-L83

Could you check the logs for this function (they should be in a log group named _/aws/lambda/stackname-profiler_) to see what template was chosen?

**Comment by sadikay** [comment]
Ohh. Thx @dscpinheiro. It's my mistake. The output was `undefined`. 
I changed the configs from **16x9** to **9x16** for mobile vertical view. There was a missing configuration in the profiler. Now it's fixed.

If someone else interested in mobile vertical view here is my fork: https://github.com/svhawks/video-on-demand-on-aws

Thx!
