### ISSUE TITLE
Add support for captions/subtitles

### ISSUE THREAD

**Issue by maduggan** [awslabs/video-on-demand-on-aws#56]
Enjoying the project and using it a lot. Up to this point we've been burning subtitles into the videos themselves (which has been fine), but we recently got the request for more languages being supported. I know that mediaconvert supports subtitles but has anyone modified this project to support passing in those files or does the project intend to in the future?

I'm also not against doing that work myself if there's no interest in supporting that as a feature. Thanks for your time.

**Comment by dscpinheiro** [comment]
Hi @maduggan,

No, unfortunately that's not supported at the moment (you can pass a custom template to the workflow but creating one for each video would not scale well).

I'll keep the issue open, and if there's more interest we'll add this feature request to our backlog.

**Comment by tariqinaam** [comment]
Hi,
is there any viable workaround to ingest substile (external files) later in the process, say at packaging time.
We have a requirement where asset is available however subtitle files comes later during the week . 

We currently holding on to implement the solution due to this blocker. I am open to any workaround if anyone can suggest.
thanks

**Comment by maduggan** [comment]
So what we did was to handle this on the client side instead of attempting to bake the subtitles into the file with media convert. In essence we just load the client-side player with video.js to allow HLS to work everywhere and then pass it the subtitle file at that time. This seemed easier than the AWS solution. The only downside is you do need WebVTT subtitle files but they're pretty simple to convert.

**Comment by tariqinaam** [comment]
I thought of this workaround, however, in our scenario, delivery is consumed by various apps (e.g smart tv, roku) which require CC within the manifest file.
thanks for the suggestion though.

**Comment by ewanuno** [comment]
> No, unfortunately that's not supported at the moment (you can pass a custom template to the workflow but creating one for each video would not scale well).
>

could a job template be provided via the manifest for each video file?

**Comment by tomnight** [comment]
Request has been add to our backlog, closing old issue
