### ISSUE TITLE
Feature Request: Ability to use already existing Destination S3 Bucket when deploying new stack

### ISSUE THREAD

**Issue by skawirat** [awslabs/video-on-demand-on-aws#58]
Hi Daniel,

We recently upgraded our VOD workflow from version 4 to 5.0.0 Everything went smoothly with the exception of the below.

In the previous version 4 stack we had multiple assets generated and made available to customers via CDN.  

Requirement:
Even after we deploy the new version 5.0.0 stack we still wanted customers to be able to have access to previous assets. 

Issue:
As you are aware each time, we deploy a new VOD on demand stack it generates a new destination bucket. So if we want to make previous assets available to user then we had to copy the asset from previous destination bucket to new bucket.

Due to the very large number of assets we had it took us a little over 4 1/2 days to copy the assets from previous destination bucket to new destination bucket.

I was wondering if you can update the CloudFormation template such that

IF destination_bucket_speficied_by_user THEN
   use already existing destination bucket
ELSE
   created new destination bucket
END

Thanks

Sam

**Comment by dscpinheiro** [comment]
Hi @skawirat,

We can add this to backlog, but you can already specify a different destination bucket if you use the Metadata option:
```json
{
  "srcVideo": "video.mp4",
  "destBucket": "other-bucket"
}
```

The only requirement for this to work is that the MediaConvert / MediaPackage roles need to have access to this bucket as well.

**Comment by skawirat** [comment]
Hi @dscpinheiro,

Thanks for your respopnse
I totally overlooked the destination bucket option when I did the migration to new VOD 5.0.0 stack.

Since your response, I have now tested out the destBucket option and confirmed for myself that I can use it when deploying a new stack so that the bucket from previous stack still gets used for saving assets which in turn eliminates the need for copying assets from previous S3 bucket to new.

As destBucket bucket option satisfies my requirement; I would probably say updating CloudFormation  template the accept a destination bucket option is no longer much of requirement hence I will withdraw  my feature request.

Thanks

Sam

**Comment by ffiore1** [comment]
> Hi @dscpinheiro,
> 
> Thanks for your respopnse
> I totally overlooked the destination bucket option when I did the migration to new VOD 5.0.0 stack.
> 
> Since your response, I have now tested out the destBucket option and confirmed for myself that I can use it when deploying a new stack so that the bucket from previous stack still gets used for saving assets which in turn eliminates the need for copying assets from previous S3 bucket to new.
> 
> As destBucket bucket option satisfies my requirement; I would probably say updating CloudFormation template the accept a destination bucket option is no longer much of requirement hence I will withdraw my feature request.
> 
> Thanks
> 
> Sam

I think the bucket requirement is a nice one and should be part/step of an overall update stack process.

The update stack process possibly should allow to:
1) keep the same bucket and related urls
2) keep the same DynamoDb tables or, alternatively, migrate the data from the old format to the new format in new tables

if that is not the direction the solution is going to (I mean, a backwards compatible update stack process) , ideally that should be clarified so that everyone , as we did, will implement from day 1 / think about possible workarounds (wrap / map with external tables, etc.) when implementing the solution, I reckon.

**Comment by dscpinheiro** [comment]
Thanks for the feedback @ffiore1 and @skawirat.

For future releases, we'll make the update process more backwards compatible.
