### ISSUE TITLE
Is there a way to have input stitching done via json?

### ISSUE THREAD

**Issue by tapanjo92** [awslabs/video-on-demand-on-aws#64]
Can you pass 2 videos in one JSON file wherein it will stitch the two videos together?

**Comment by dscpinheiro** [comment]
Hi @tapanjo92,

No, this is not possible at this time. By default, the solution assumes there's only one input file. 

I can add this feature request to our backlog if there's enough interest.

**Comment by tapanjo92** [comment]
@dscpinheiro 
Thank You very much!
