### ISSUE TITLE
getting an error with input(.json file in s3)

### ISSUE THREAD

**Issue by tapanjo92** [awslabs/video-on-demand-on-aws#65]
I have modified my 'encode-lambda', which enables 'input-clippings' and works perfectly whenever I input 'start' and 'stop' time in .json file.
But the workflow fails if I don't mention the 'start-stop' time in the .json file (for eg. I might not want to cut some videos).
Is the because of the media convert's internal structure?

` Settings: {
                Inputs: [{
                    InputClippings: [{
                        EndTimecode: event.specifiedEnd,
                        StartTimecode: event.specifiedStart
                    },
                         {
                        EndTimecode: event.specifiedEnd1,
                        StartTimecode: event.specifiedStart1
                    }],`

**Comment by dscpinheiro** [comment]
Hi @tapanjo92,

From the MediaConvert docs (https://docs.aws.amazon.com/mediaconvert/latest/apireference/jobs.html#jobs-model-inputclipping), it looks like "_Start timecode or End timecode may be left blank, but not both_".

That's probably the reason your job is failing if you don't specify the _start-stop_ property.

**Comment by aassadza** [comment]
We are closing this issue, but please feel free to open the issue again if you need any other support.
