### ISSUE TITLE
The workflow does not encode 'AVC' file

### ISSUE THREAD

**Issue by tapanjo92** [awslabs/video-on-demand-on-aws#68]
Hi,

I tried passing a video which had avc as a video stream, and the encode lambda was not able to recognise it. It gave, 'missing parameter' error.
When I created a manual job of the same video, it converted successfully.
I was wondering if there is any problem with the function in identifying the 'avc' file?

Thank You!!

**Comment by dscpinheiro** [comment]
The missing parameter error message is likely coming from the _mediaconvert.createJob_ API call.

One thing you can do is compare the settings from the two jobs (the one that failed and the one that didn't) to see what's different between them. Here's how you can do that in the console:

<img width="824" alt="Screen Shot 2020-03-27 at 9 58 39 AM" src="https://user-images.githubusercontent.com/3842788/77763584-3864e200-7033-11ea-8cee-c063b575694e.png">

**Comment by tapanjo92** [comment]
Hi Daniel,

The problem is, jobs which have AVC or MOV are not even reaching the Mediaconvert, they are failing at Encoding. 
![f1](https://user-images.githubusercontent.com/49943773/77809217-eda2a300-70e2-11ea-8a0b-f3724fdc5a7f.png)
![f2](https://user-images.githubusercontent.com/49943773/77809223-f1362a00-70e2-11ea-916c-57796f5db366.png)
![f3](https://user-images.githubusercontent.com/49943773/77809230-f5fade00-70e2-11ea-8c79-f2d1fcd21086.png)

**Comment by dscpinheiro** [comment]
Sorry for the misunderstanding, I thought the MediaConvert job was throwing an error.

Looking at the create-job API (https://docs.aws.amazon.com/cli/latest/reference/mediaconvert/create-job.html), the only option that has a _name_ property is _OutputGroups_, so here's what I'd do to double check:

Modify the encode function to log the parameters before calling create-job, that is, change this:
https://github.com/awslabs/video-on-demand-on-aws/blob/97049f1d9a551f7dd357e1eedc3f075d11fa67ce/source/encode/index.js#L228

To this:
```javascript
console.log(`SETTINGS:: ${JSON.stringify(job.Settings, null, 2)}`);
let data = await mediaconvert.createJob(job).promise();
```

By doing that, you should be able to get the failings parameters (in CloudWatch), compare them with a successful job, and (hopefully) spot the difference.
