### ISSUE TITLE
Just deployed the function in Mumbai (ap-soth-1) and getting this error

### ISSUE THREAD

**Issue by lakeshh04** [awslabs/video-on-demand-on-aws#69]
Hi,

I want to pass metadatafile, but getting this error -:
{
  "error": "TypeError",
  "cause": {
    "errorMessage": "'NoneType' object is not subscriptable",
    "errorType": "TypeError",
    "stackTrace": [
      "  File \"/var/task/lambda_function.py\", line 157, in lambda_handler\n    raise err\n",
      "  File \"/var/task/lambda_function.py\", line 124, in lambda_handler\n    tracks = json_content['media']['track']\n"
    ]
  }
}

**Comment by dscpinheiro** [comment]
Hi @lakeshh04,

The error is probably happening when pre-signing the S3 url. 
We're tracking this problem in #67.

**Comment by lakeshh04** [comment]
Oh, yes I am getting the same error when deployed in Mumbai region, but no error in US region
Thank you
