### ISSUE TITLE
build-s3-dist.sh failing usage error

### ISSUE THREAD

**Issue by RaNhO21** [awslabs/video-on-demand-on-aws#70]
When I run "./build-s3-dist.sh github-test-idk-wat-imdoing video-on-demand-on-aws v5.0.0-custom", following every step on the readme, I get this output :

<img width="587" alt="Captura de Tela 2020-04-04 às 04 20 23" src="https://user-images.githubusercontent.com/48166207/78421104-9beea100-762b-11ea-8eb0-de0d541f2edb.png">

Idk how to fix it, does anyone have any idea ?

edit: 
I tried to debug it and its failing right on "cp $template_dir/video-on-demand-on-aws.yaml $template_dist_dir/video-on-demand-on-aws.template"

**Comment by dscpinheiro** [comment]
Hi @RaNhO21,

Unfortunately I couldn't reproduce the problem locally. I downloaded the repository, and this is what I get when running that same command:

```console
$ pwd
~/video-on-demand-on-aws/deployment

$ ls
build-s3-dist.sh            run-unit-tests.sh           video-on-demand-on-aws.yaml

$ ./build-s3-dist.sh github-test-idk-wat-imdoing video-on-demand-on-aws v5.0.0-custom
------------------------------------------------------------------------------
Rebuild distribution
------------------------------------------------------------------------------
------------------------------------------------------------------------------
CloudFormation Template
------------------------------------------------------------------------------
sed -i -e s/%%BUCKET_NAME%%/github-test-idk-wat-imdoing/g
sed -i -e s/%%SOLUTION_NAME%%/video-on-demand-on-aws/g
sed -i -e s/%%VERSION%%/v5.0.0-custom/g
------------------------------------------------------------------------------
Lambda Functions
------------------------------------------------------------------------------
...
------------------------------------------------------------------------------
S3 Packaging Complete
------------------------------------------------------------------------------
```

Did you change (modify / move) the _video-on-demand-on-aws.yaml_ file?

**Comment by RaNhO21** [comment]
I didn't modify anything, also I downloaded it and tryied again and the error still
I'm using macOS 10.15.3, tryied it on zsh and standard shell
If you need any other info just tell me

If you are on linux, probably the cp command is diferent, as macOS comes from BSD the cp command comes from bsd as well, idk the differences but there is a chance of that case

**Comment by dscpinheiro** [comment]
I'm also on MacOS (but on version 10.14.6), and running the commands you listed works.

Could you check the deployment folder to see if the _global-s3-assets_ and _regional-s3-assets_ folders were created?

**Comment by RaNhO21** [comment]
They weren't created, I updated to 10.15.4 and I get this error. I don't have a minimum ideia why this is happening now haha
Do you think that its something from my computer affecting it ?

**Comment by RaNhO21** [comment]
I tryied it and I get the error right on cp $template_dir/video-on-demand-on-aws.yaml $template_dist_dir/video-on-demand-on-aws.template

But it worked on an EC2 instance so its fine, thanks for the suggestion !!!
