### ISSUE TITLE
I made changes in the template and tried to deploy as change set and it never work. 

### ISSUE THREAD

**Issue by morwalz** [awslabs/video-on-demand-on-aws#73]
Hi, 

CustomResource attribute error: Vendor response doesn't contain GroupId key in object arn:aws:cloudformation:ap-south-1:941275879372:stack/examsbook-mumbai/286d76e0-7c28-11ea-907d-06184e58d994\|MediaPackageVod\|26ef7a76-d963-4d4b-8b75-21f482e699dc in S3 bucket cloudformation-custom-resource-storage-apsouth1
--

**Comment by tomnight** [comment]
Hi,
Its a little hard to figure out what went wrong with only the snippet above. Can you explain the changes you made to the template?

**Comment by tomnight** [comment]
closing as inactive, please reach out if you still need assistance.

**Comment by abdullah432** [comment]
Same issue. I'm stuck with error from 4 days. Not able to figure it out.
When I try to create/deploy stack in cloudformation. It fails with the following event:
**LogicalID:** MediaPackageVod
**Status:** CREATE_FAILED
**Status reason: ** Failed to create resource. See the details in CloudWatch Log Stream: 2020/08/04/[$LATEST]61666febbb04499aba17e097b984b2e5

**Inside this log I get following error**
{
    "message": "internal server error",
    "code": "InternalServerErrorException",
    "time": "2020-08-04T15:37:35.622Z",
    "requestId": "dfffa7cc-bba8-44ae-bec4-507a8cc822af",
    "statusCode": 500,
    "retryable": true
}
