### ISSUE TITLE
workflow Status:: Error : "Cannot read property '0' of undefined" when uploading file to source-bucket via browser

### ISSUE THREAD

**Issue by ArkageAWS** [awslabs/video-on-demand-on-aws#74]
Hello to everyone,

I am wasting days trying to figure it out where I could debug this TypeError I receive upon uploading a video file to my bucket, with VIDEO ON DEMAND solution.

this is the core part
```
$file_path = $temp_name.".".$file_ext;
$key = basename($file_name);

try {
		$result = $s3Client->putObject([
				'Bucket' => $bucket,
				'Key' => $key,
				'Body' => $file_path,
				'ContentType' => $file_mime_type
		]);
		$output['ok'] = $bucket."|".$file_path."|".$key;
	} catch(S3 $e) {
		$output['error'] = $e->getMessage();
	}
```
what it happens is that I receive the INGEST email with all data BUT then i receive the error message: 
```

{
  "guid": "831072ba-6ebe-415c-97bd-7706b0568c14",
  "workflowStatus": "Error",
  "workflowErrorAt": "AVOD-profiler",
  "errorMessage": "TypeError: Cannot read property '0' of undefined",
  "errorDetails": "https://console.aws.amazon.com/cloudwatch/home?region=eu-central-1#logStream:group=/aws/lambda/AVOD-profiler"
}
```

everything works fine by uploading files from S3 bucket online interface...

any hint?

**Comment by tomnight** [comment]
Thanks for reaching out.
I think is an issue is with the code snippet you have above, I don't think 'Body' => $file_path, is correct. Body should be the actual file not the path to the file no?

**Comment by ArkageAWS** [comment]
Hi,

no it is correct, as it uploads correctly the file in the first bucket, the
"source" one.
I don't understand what it is missing, that blocks the ingested file to be
processed and pass to the encoding stage and then to the "destination"
bucket... :/

*matteo maria ambrogi*
chief innovation officer

[image: Arkage - Artattack Group]

*t* +39 06 87911001
*m* +39 346 8126 520
*w* website <http://www.arkage.it/> *b* blog <http://stream.arkage.it/blog>
*fb* @thearkage <https://www.facebook.com/thearkage>
*tw* @thearkage <https://twitter.com/thearkage>
*vm* @arkageplay <https://vimeo.com/arkageplay>


[image: Bcorp - business as a force for good]
<https://www.linkedin.com/feed/update/urn:li:activity:6628936712816996353/>

Siamo una B Corp: il nostro obiettivo
è arrivare a zero emissioni entro il 2030.
<https://www.linkedin.com/feed/update/urn:li:activity:6628936712816996353/>


Il giorno lun 27 apr 2020 alle ore 22:46 Tom Night <notifications@github.com>
ha scritto:

**Comment by ArkageAWS** [comment]
one step ahead in debugging have been made by inspecting entries in DynamoDB.

srcMediaInfo are completely different between browser uploaded ones:

```
srcmediaInfo: {\n  \"filename\": \"2-2.mov\",\n  \"container\": {\n    \"fileSize\": 49\n  }\n}
```

and the S3 directly loaded ones, whose workflow delivers an encoded output in the dest-bucket.

```
srcmediaInfo: {\n  \"filename\": \"demo999.mp4\",\n  \"container\": {\n    \"format\": \"MPEG-4\",\n    \"fileSize\": 13706486,\n    \"duration\": 2.0,\n    \"totalBitrate\": 54825944\n  },\n  \"video\": [\n    {\n      \"codec\": \"AVC\",\n      \"profile\": \"Main@L4.2\",\n      \"bitrate\": 53994228,\n      \"duration\": 2.0,\n      \"frameCount\": 100,\n      \"width\": 1920,\n      \"height\": 1080,\n      \"framerate\": 50.0,\n      \"scanType\": \"Progressive\",\n      \"aspectRatio\": \"1.778\",\n      \"bitDepth\": 8,\n      \"colorSpace\": \"YUV 4:2:0\"\n    }\n  ],\n  \"audio\": [\n    {\n      \"codec\": \"AAC\",\n      \"bitrate\": 384000,\n      \"duration\": 2.0,\n      \"frameCount\": 94,\n      \"bitrateMode\": \"CBR\",\n      \"language\": \"en\",\n      \"channels\": 2,\n      \"samplingRate\": 48000,\n      \"samplePerFrame\": 1024\n    }\n  ]\n}
```

**Comment by stubbornspace** [comment]
So the 2-2.mov file is on 49bits according to the mediainfo output in dynamodb, This isn't large enough to be a valid video file.   I think you're only uploading a partial file. 
Try uploading the file through you code and then download it and see if it will play?

**Comment by ArkageAWS** [comment]
Guys I managed to solve by using the snippet MultipartUploader($s3...!!!
it works fine with any kind of filesize.

I have just implemented the stream version, with
```
...
$source = fopen($_FILES['file']['tmp_name'], 'rb');
$uploader = new MultipartUploader($s3Client, $source, [
...
```

which should be better to upload in multipart the files, in a direct stream
without copying them in local storages, correct?

ty and best


*matteo maria ambrogi*
chief innovation officer

[image: Arkage - Artattack Group]

*t* +39 06 87911001
*m* +39 346 8126 520
*w* website <http://www.arkage.it/> *b* blog <http://stream.arkage.it/blog>
*fb* @thearkage <https://www.facebook.com/thearkage>
*tw* @thearkage <https://twitter.com/thearkage>
*vm* @arkageplay <https://vimeo.com/arkageplay>


[image: Bcorp - business as a force for good]
<https://www.linkedin.com/feed/update/urn:li:activity:6628936712816996353/>

Siamo una B Corp: il nostro obiettivo
è arrivare a zero emissioni entro il 2030.
<https://www.linkedin.com/feed/update/urn:li:activity:6628936712816996353/>


Il giorno mar 28 apr 2020 alle ore 17:22 Bob <notifications@github.com> ha
scritto:

**Comment by stubbornspace** [comment]
That make sense, glad to hear you got it working!

**Comment by ArkageAWS** [comment]
FIRST OF ALL THIS GUYS DID A HUGE AMAZING JOB, in any case.

goddblessyahall.

said that: my upoader is working even better with MultiPart and fopen, at
least, it should stream directly without saving in a temp folder, correct?
then, why am i receiving a 504 error on larger files?

*matteo maria ambrogi*
chief innovation officer

[image: Arkage - Artattack Group]

*t* +39 06 87911001
*m* +39 346 8126 520
*w* website <http://www.arkage.it/> *b* blog <http://stream.arkage.it/blog>
*fb* @thearkage <https://www.facebook.com/thearkage>
*tw* @thearkage <https://twitter.com/thearkage>
*vm* @arkageplay <https://vimeo.com/arkageplay>


[image: Bcorp - business as a force for good]
<https://www.linkedin.com/feed/update/urn:li:activity:6628936712816996353/>

Siamo una B Corp: il nostro obiettivo
è arrivare a zero emissioni entro il 2030.
<https://www.linkedin.com/feed/update/urn:li:activity:6628936712816996353/>


Il giorno mar 28 apr 2020 alle ore 17:31 Bob <notifications@github.com> ha
scritto:

**Comment by tomnight** [comment]
closing old thread
