### ISSUE TITLE
Workflow fails is video has no input

### ISSUE THREAD

**Issue by ArkageAWS** [awslabs/video-on-demand-on-aws#75]
hello all,

I don't know if it is wanted or if there's some kind of fallback I didn't adopted yet, but upon loading video with no audio tracks the ingest workflow fails with following error:

```
"errorMessage": "Invalid audio track specified for audio_selector [1]. Audio track [1] not found in input container.",
```

what can i do?

**Comment by tomnight** [comment]
MediaConvert is configured to use one of 3 templates deployed by the solution, these templates require at lease one audio track to exist in the source file. If you need support for this then you will need to update the templates and the encode Lambda function to support no audio. I will add this to our backlog of options to look at. 

hope this helps.

**Comment by ArkageAWS** [comment]
CoGreat thank you: so what kind of fallback can I set up to avoid this?

*matteo maria ambrogi*
chief innovation officer

[image: Arkage - Artattack Group]

*t* +39 06 87911001
*m* +39 346 8126 520
*w* website <http://www.arkage.it/> *b* blog <http://stream.arkage.it/blog>
*fb* @thearkage <https://www.facebook.com/thearkage>
*tw* @thearkage <https://twitter.com/thearkage>
*vm* @arkageplay <https://vimeo.com/arkageplay>


[image: Bcorp - business as a force for good]
<https://www.linkedin.com/feed/update/urn:li:activity:6628936712816996353/>

Siamo una B Corp: il nostro obiettivo
è arrivare a zero emissioni entro il 2030.
<https://www.linkedin.com/feed/update/urn:li:activity:6628936712816996353/>


Il giorno lun 4 mag 2020 alle ore 16:26 Tom Night <notifications@github.com>
ha scritto:

**Comment by tomnight** [comment]
The mediainfo function extracts metadata from the source video file, you could add a simple check to validate there is a audio track listed in the output and if not throw a specific error.

**Comment by ArkageAWS** [comment]
I am working with AWS workflow though, so I don't know where I can
intercept the media-info creation
I have the same question, also to add a specific info to the uploaded
video, such as "Uploader_id", let's say that :)

*matteo maria ambrogi*
chief innovation officer

[image: Arkage - Artattack Group]

*t* +39 06 87911001
*m* +39 346 8126 520
*w* website <http://www.arkage.it/> *b* blog <http://stream.arkage.it/blog>
*fb* @thearkage <https://www.facebook.com/thearkage>
*tw* @thearkage <https://twitter.com/thearkage>
*vm* @arkageplay <https://vimeo.com/arkageplay>


[image: Bcorp - business as a force for good]
<https://www.linkedin.com/feed/update/urn:li:activity:6628936712816996353/>

Siamo una B Corp: il nostro obiettivo
è arrivare a zero emissioni entro il 2030.
<https://www.linkedin.com/feed/update/urn:li:activity:6628936712816996353/>


Il giorno lun 4 mag 2020 alle ore 17:13 Tom Night <notifications@github.com>
ha scritto:

**Comment by tomnight** [comment]
closing old thread
