### ISSUE TITLE
Very noob question

### ISSUE THREAD

**Issue by shajayesh** [awslabs/video-on-demand-on-aws#76]
The output name gets changed eg. 'Mp4_Avc_Aac_16x9_1280x720p_24Hz_4.5Mbps_qvbr.mp4'.
Is there anyway to have customized output name eg. VideoName+CustomName?

Thank You
![output](https://user-images.githubusercontent.com/64563161/80656108-b8171e00-8ac3-11ea-911c-20606ce494ef.png)

**Comment by tomnight** [comment]
The solution creates a series of MediaConvert Templates to create the set of desired outputs. Each output is named with the source file name + a name modifier for each preset. This is defined in the template for each preset as the NameModifier, for example:
```
   {
      "Preset": "_Mp4_Avc_Aac_16x9_1280x720p_24Hz_4.5Mbps_qvbr",
      "Extension": "mp4",
        "NameModifier": "_Mp4_Avc_Aac_16x9_1280x720p_24Hz_4.5Mbps_qvbr"
    }
```
You will need to update/ replace the templates. The name of the templates is stored as an environment variable for the input validate Lambda function.

Does that help?

**Comment by tomnight** [comment]
closing as inactive
