### ISSUE TITLE
Is there a way to tag the jobs?

### ISSUE THREAD

**Issue by shajayesh** [awslabs/video-on-demand-on-aws#80]
As MC can quickly add up the bill, is there a way to pass tags while passing json? Or any other way?

Thank You

**Comment by tomnight** [comment]
https://docs.aws.amazon.com/mediaconvert/latest/ug/setting-up-resources-for-catt.html

The above link explains how to tag jobs for billing purposes. You will need to update the Encode Lambda function to add the tags to the JSON payload before submitting the job to MediaConvert.

This would actually make a nice feature so we will add it to our backlog!

**Comment by tomnight** [comment]
closing as inactive, feature request has been added to our backlog.
