### ISSUE TITLE
Access Denied for All Links

### ISSUE THREAD

**Issue by stolinski** [awslabs/video-on-demand-on-aws#82]
**Describe the bug**
After running a job, all Cloudfront links are access denied. When signing the links I'm now getting "The specified key does not exist."

**To Reproduce**
Install and run. Assets are created. No way to access OOTB. I might be missing a step here as all content exists, but the documentation is a bit light on how to consume the media after it's been generated.

**Expected behavior**
I was expecting to be able to use media files via cloudfront links, but that could be an incorrect assumption. The docs don't really mention how to consume.

**Please complete the following information about the solution:**
- [ ] Version: [e.g. v1.0.0]
- [ ] Region: [e.g. us-east-1]
- [ ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? 
- [ ] Were there any errors in the CloudWatch Logs? No

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**
I was hoping for a bit more context and instruction in how to use this but nothing seems to be available online. If I'm off base in my attempt to access this content, please lmk, but I'd appreciate some help being pointed in the right direction. Either way, I ran the task, video has been correctly generate, all links are in Dynamo, none of the content is accessible even with signed urls.

**Comment by tomnight** [comment]
That for using the issue template!

You should indeed be able to playback the CloudFront URLs in a compatible player or browser. If the job completed you should have a hlsUrl item in DynamoDB which will be the HLS CloudFront URL and should be accessible, the S3 links will not work as the bucket and assets are not public.

* Which player / browser are you using?
* Which parameters did you select when launching the 
* Are there any spaces, special characters in the source filename that might have break the URL
* Can you manually browse to the files in S3 and confirm the content is in S3?
* Can you try the HLS and Or Dash Urls with this test player:

https://bitmovin.com/demos/stream-test

**Comment by stolinski** [comment]
It's def not accessible. I was actually using bitmovin's stream test to try with `https://levelyp-destination-1rlmp2aypgyo6.s3.amazonaws.com/0bd4c5bd-9d9d-4ad2-bda7-2e61aeb3926a/dash/%236+A+Word+On+Organization.mpd`

There is a special character in the content, but I didn't think that would lead to an access denied error. Browser is chrome, player is just the test one you linked here.

**Comment by tomnight** [comment]
That’s the s3 url, those are not accessible but stored in dynamo as these are the outputs from mediaconvert. The links you want are https://.....cloudfront.net/......

Also it looks like your original file may have had spaces in the name. I would recommend not having spaces in the file names. 

Try the cloudfront urls and if they don’t work try uploading a new video without spaces.  

Thanks

**Comment by stolinski** [comment]
My apologies on the link. `https://d1zcfe0406qsgn.cloudfront.net/0bd4c5bd-9d9d-4ad2-bda7-2e61aeb3926a/dash/#6 A Word On Organization.mpd` was the cloudfront link. 

Will having spaces in filenames cause auth errors?  I'll throw a new file up and see if I'm getting the same access issues.

**Comment by tomnight** [comment]
The workflow will still work but I recommend you don't user files with spaces as this will cause errors on playback because your creating HTTPS links with spaces in. 

If that's problematic for you, You could use the MediaPackage  options as MediaPacakge will generate links without the spaces.
