### ISSUE TITLE
DASH not being created

### ISSUE THREAD

**Issue by ChrisCacace** [awslabs/video-on-demand-on-aws#85]
**Describe the bug**
The DASH video is not being created when Enable MediaPackage is checked. It is absent in the job templates for MediaConvert. The Output Presets still exist, but they are not being used. I noticed that the "PackageType" preset for deployment was taken away from version 4.3 -> 5.1 

**To Reproduce**
Create the CloudFormation with Enable Media Package
and check the MediaConvert.

**Screenshots**
![Screen Shot 2020-05-29 at 12 50 43 PM](https://user-images.githubusercontent.com/48874864/83284710-1579ba00-a1ab-11ea-819a-96ac4b89a4e4.png)
![Screen Shot 2020-05-29 at 12 50 54 PM](https://user-images.githubusercontent.com/48874864/83284736-1ca0c800-a1ab-11ea-830e-2f3d93d48a39.png)

**Comment by tomnight** [comment]
Enabling MediaPackage configures the workflow to use a different set of templates that only create the HLS and MP4 content. MediaPackage is then configured to ingest the HLS content from S3 and package it into MSS, DASH or CMAF based on demand. 

If you check the DynamoDB table you should see a section for egressEndpoints which includes the CloudFront links for each format.

Hope this helps.

**Comment by tomnight** [comment]
Closing as inactive and not a bug.
