### ISSUE TITLE
After initial setup, videos are not being processed and Notification Email Address only receives a single email

### ISSUE THREAD

**Issue by sagannotcarl** [awslabs/video-on-demand-on-aws#86]
**Describe the bug**
I am following the implementation guide, and after going through the deployment process (once selecting some options such as MediaPackage and once with all default options) I am unable to get any videos to process.

In addition I only receive a single email to the Notification Email Address confirming a subscription while the guide says I should receive three subscription notifications.

**To Reproduce**
- Open Video on Demand on AWS pdf
- Click Launch Solution button
- Follow prompts
- Upload a video to the xxxx-source bucket

**Expected behavior**
- Video should be processed and something should be on the destination bucket

**Please complete the following information about the solution:**
- [x] Version: v5.1.0
- [x] Region: us-east-1
- [x] Was the solution modified from the version published on this repository? **No**
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [x] Were there any errors in the CloudWatch Logs? **No**

**Comment by ankur140290** [comment]
I am facing the same issue with custom build option.

**Comment by jorgefcosta** [comment]
I got the same issue because I had choose the metadata option in the Cloudformation Template. Try to deploy it again and change the metadata option by video option. “ Choose VideoFile to ingest source videos only; choose MetadataFile to ingest metadata files and source videos.”

**Comment by sagannotcarl** [comment]
@jorgefcosta For me both times I tried to set this up I chose the VideoFile option. Uploading a file didn't trigger any workflow for me. 

Do you know which component is supposed to initiate workflow and respond to the file upload? While debugging this problem I couldn't find anything responding to the file upload.

**Comment by sagannotcarl** [comment]
Is there anything in this template that is not available to a free tier account?

**Comment by tomnight** [comment]
The template should work in a free tier account, this doesn't restrict access to anything it just gives you free access to certain resources.

The video upload selected as part of the deployment, uploading a video to the source bucket should trigger the step-functions lambda function which will then invoke the ingest Step Functions. Couple of questions/things to check:

1. File extension & triggers
If you go to the source S3 bucket in the console and select > properties > events you should see 5 triggers for 5 different file types; .mpg .mp4. mv4 .mov .m2ts. What file extension is you video? if its not one of these the workflow won't get triggered (you can always add a new event trigger if needed.) 

2. Lambda CloudWatch logs
The lambda function that triggers the workflow should be called <stackname>-step-functions. if you got to the function in the console > select monitoring > view CloudWatch logs. Check to see if the function was ever invoked and if there were any errors. 

Let me know if this helps?

**Comment by sagannotcarl** [comment]
Thank you @tomnight, knowing how to find the events that trigger the ingest workflow was very helpful.

I had previously checked the file extension as a possible issue but looking at the actual S3 events I now see I had a capitalized .MOV file instead of lowercase. Renaming my file to the lowercase .mov fixed my problem.
