### ISSUE TITLE
Cloudfront CORS policy

### ISSUE THREAD

**Issue by phillee** [awslabs/video-on-demand-on-aws#87]
Apologies in advance for the noob question, but I've searched around and haven't found resources on this. 

**Describe the bug**
I've followed the steps and the video is encoded successfully. I can access the hlsUrl if I directly open it in my player. However, if I try embedding it into my webpage (on localhost), I get blocked by the CORS policy: 
```
Access to XMLHttpRequest at .... from origin 'http://localhost:1337' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

How do I whitelist the CORS policy? On the S3 bucket, * is already allowed.

**Comment by tomnight** [comment]
CORS is configured on the CloudFront distribution so I think this is likely to be a local issue, if you testing then try disabling cors origin for local host in your browser. The steps are slightly different for different browsers but usually found under the developer tools.

**Comment by ankur140290** [comment]
Hi @phillee  
Open the file : source/custom-resource/lib/mediapackage/cloudfront.js and update the Headers param as following: 


```
Headers: {
                    Quantity: 4,
                    Items: [
                        'Access-Control-Allow-Origin',
                        'Access-Control-Request-Headers',
                        'Access-Control-Request-Method',
                        'Origin'
                    ]
                },
```

This will update your cloudfront config and allow CORS calls.

**Comment by phillee** [comment]
Thank you!
