### ISSUE TITLE
HLS Output files doesn't use Follow-source on framerate, always use 30fps

### ISSUE THREAD

**Issue by HenrikJay** [awslabs/video-on-demand-on-aws#89]
**Describe the bug**

**To Reproduce**
Upload mp4 with 23.976 or 24 FPS and output to HLS.

**Expected behavior**
Should follow source on framerate but Output1 get's 15fps and  everything else 30fps.
Logs confirm that input from StepFunction to convert is accurate but response shows as 30fps.

**Please complete the following information about the solution:**
- [ ] Version: [e.g. v1.0.0] - Current
- [ ] Region: [e.g. us-east-1] - us-east-1
- [ ] Was the solution modified from the version published on this repository? - No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub? - No
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? - Yes
- [ ] Were there any errors in the CloudWatch Logs? - No

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by tomnight** [comment]
Thanks for reaching out, the lowest bitrate version (270p) is a lower framerate than the others. We will be reviewing the encoding templates in the next release and will look at the follow source option.

**Comment by tomgilman** [comment]
Closing this issue.  We'll plan on instructions on changing template values in upcoming documentation.
