### ISSUE TITLE
How to control costs?

### ISSUE THREAD

**Issue by phillee** [awslabs/video-on-demand-on-aws#90]
**Describe the bug**
I encoded a 3 hour video using the default deployment and was charged $100.

$0.024/min - US West (Oregon) - HD, AVC/H.264, <=30 fps, Single pass HQ, Pro Tier 2,877.121 minutes $69.05
$0.012/min - US West (Oregon) - SD, AVC/H.264, <=30 fps, Single pass HQ, Pro Tier 2,293.903 minutes $27.53

I expected a 3 hour video to cost somewhere around $4 (180 minutes * 0.024/min). Obviously there is more happening in this deployment than I expected. Looks like this is also not an uncommon issue: https://github.com/awslabs/video-on-demand-on-aws/issues/48

Suggestions:
* It would be great if the documentation gives a clear indication of expected cost with the default configuration.
* Even better, can you provide suggestions of a more cost conscious configuration?
* Finally, where can I configure the settings for a deployment? (less outputs, disabling acceleration, etc). 

**To Reproduce**
Template defaults

**Expected behavior**

**Please complete the following information about the solution:**
- [ ] Version: [e.g. v1.0.0]
- [ ] Region: [e.g. us-east-1]
- [ ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by jacknely** [comment]
You need to edit mediaconvert service in custom resources to remove output formats (Templates & Presets) that are not desired. Alternatively, you can remove them manually after deployment in the Media Convert service in the console.

**Comment by tomnight** [comment]
sorry if the cost were misleading, we will review both the documentation and the encoding templates in the next release to insure this is more clear. 

Jacknely is correct the cost is determined by a number of factors but the number of outputs has the largest impact. there are 3 Encoding templates shipped with the solution which create up to 7 ABR version of HLS and Dash plus 2 mp4 outputs. I would recommend removing anything you don't need or creating your own templates to tailor the outputs to your needs.

**Comment by tomnight** [comment]
closing old issue
