### ISSUE TITLE
How to integrate DRM protection

### ISSUE THREAD

**Issue by numToStr** [awslabs/video-on-demand-on-aws#91]
**Is your feature request related to a problem? Please describe.**
I am using this template and Its awesome. I would like to integrate DRM protection for the videos. How can I do that with the workflow listed below? 

- Without Media Package
- With Media Package.

I am new to media stuff. Any help would be appreciated.

**Comment by tomnight** [comment]
Without MediaPackage: https://docs.aws.amazon.com/mediaconvert/latest/ug/using-encryption.html
You would need to update the encoding templates and possibly the encode lambda function to incorporate DRM into the Jobs submitted to Elemental MediaConvert.  I would suggest creating a job with you DRM settings and then use this as a reference for updating the templates. 

With MediaPackage: https://docs.aws.amazon.com/mediapackage/latest/ug/data-protection.html

This might be the easier route as you can configure and manage the DRM configuration through MediaPackage VOD. with this option enabled the  solution creates 4 packaging groups in MediaPackage VOD. You will need to update each of these to include you encryption setting.

Hope this helps.

**Comment by tomgilman** [comment]
Closing this issue as DRM is not planned for this project.
