### ISSUE TITLE
How to integrate Ad 

### ISSUE THREAD

**Issue by ebinbabu** [awslabs/video-on-demand-on-aws#92]
**Is your feature request related to a problem? Please describe.**
I am using this template and Its awesome. I would like to integrate Ads in videos. How can I do that with the workflow?

I am new to media stuff.

**Comment by tomnight** [comment]
MediaConvert does support Ad insertion, the easiest way to do this is to include the scte-35-markers in you source file and then update the settings in the templates used by the solution to PASSTHROUGH. 

https://docs.aws.amazon.com/mediaconvert/latest/ug/passing-through-scte-35-markers.html

To do this navigate to the MediaConvert console and under Output Presets you should see all of the presets created by the solution. These are referenced by the 3 templates used by the solution and include the configuration for each output group. For each one select the preset > update preset > Advanced > and set SCTE-35 source to PASSTHROUGH.

note: this only applies to the HLS and DASH outputs.

hope this helps.

https://docs.aws.amazon.com/mediaconvert/latest/ug/including-scte-35-markers.html

**Comment by ebinbabu** [comment]
thank you
