### ISSUE TITLE
Workflow not triggering with MOV

### ISSUE THREAD

**Issue by ArkageAWS** [awslabs/video-on-demand-on-aws#93]
**The bug**
The workflow is not triggering if user uploads .MOV video

**To Reproduce**
Just upload a MOV video

**Expected behavior**
Same as for mp4 video

**Please complete the following information about the solution:**
not needed

**Comment by tomnight** [comment]
The workflow is triggered by an event notification configured on the source S3 bucket which invokes the step functions lambda function. There are 5 event notification setup for .mp4, .mov, .m2ts, .mv4 and .mpg. These are case sensitive so .MOV is not triggering the workflow. You can either rename the file to .mov or update/add an event notification for .MOV.

The settings are found in the S3 console, select the source S3 bucket > Properties Events (under advanced settings). 

details on event notifications in S3: https://docs.aws.amazon.com/AmazonS3/latest/dev/NotificationHowTo.html

Hope this helps

**Comment by ArkageAWS** [comment]
works quite like a charm!!! <3

the only issue is that uploading the MOV, it seems it is not rotated correctly...
and remains "landscape" even if took vertical on mobile phone...

**Comment by tomnight** [comment]
The MediaConvert templates used by the solution are set to 16:9 and not portrait. If you want to use portrait video you''ll need to create new encoding templates: 

https://docs.aws.amazon.com/mediaconvert/latest/ug/working-with-job-templates.html

**Comment by tomnight** [comment]
closing old thread
