### ISSUE TITLE
Questions regarding the streaming solution

### ISSUE THREAD

**Issue by divyasinghal1** [awslabs/video-on-demand-on-aws#95]
I believe that the architecture can be further optimized to be more cost effective.
The Lambda which is responsible for orchestrating the various Stepfunction workflows AKA the [Stepfunction Lambda](https://github.com/awslabs/video-on-demand-on-aws/blob/master/source/step-functions/) invokes the Stepfunction and waits for the promise to be settled. The Lambda then idles till the promise is fulfilled, i.e. the StepFunction workflow is completed. Additionally, The ingest workflow, triggers another instance of the Stepfunction Lambda which [triggers the Process workflow](https://github.com/awslabs/video-on-demand-on-aws/blob/master/deployment/video-on-demand-on-aws.yaml#L1379). So the StepLambda instance responsible for triggering Ingest Workflow does not finish execution till the process workflow is completed. This can lead to additional overhead in costs and can lead to lambdas getting timed out if a new processing heavy synchronous component is introduced in the workflow.

I also had a few additional questions about the reason some choices were made:
- Why are stepfunctions used in this case instead of a single lambda to handle each workflow? 

- In case of the process workflow, Several of the choices are defined as type: "Pass" [such as accelerated transcode check](https://github.com/awslabs/video-on-demand-on-aws/blob/master/deployment/video-on-demand-on-aws.yaml#L1463). Are these choices are taken into consideration in the [Encode Lambda](https://github.com/awslabs/video-on-demand-on-aws/tree/master/source/encode).  What is the reason that these choice and steps are included as steps in the workflow state machine?

Thank you for your time.

**Comment by tomnight** [comment]
Thanks for reaching out. 

First to clarify the Lambda function which triggers the state machine is not waiting for the state machine to complete, its just waiting for a response to call to execute the state machine, a success /error response. If you look at the sdk docs you'll see that the startExecution API just returns the date the execution is started.

https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/StepFunctions.html#startExecution-property

The reason for using Step Functions was to break the lambda function down to make it easier to understand each of the steps, visualize the workflow and make it easy to customize the solution buy  adding/remove components.

hope this helps, 

We will review you feedback in the next release

**Comment by tomnight** [comment]
closing old thread
