### ISSUE TITLE
 Pricing details

### ISSUE THREAD

**Issue by ebinbabu** [awslabs/video-on-demand-on-aws#97]
Hi
Can I get Pricing Details of this template or please to help me calculate the cost.
any kind of information appreciated
Thank you

**Comment by ebinbabu** [comment]
@tomnight  Hi can you help me

**Comment by ashadnasim52** [comment]
You are responsible for the cost of the AWS services used while running this reference deployment. The total cost for running this solution depends on the size of your videos, the delivery option you choose, and the number of requests for each video. **The majority of the cost will come from AWS Elemental MediaConvert.** For more information about MediaConvert pricing, refer to the  MediaConvert documentation. Prices are subject to change. For full details, see the pricing webpage for each AWS service you will be using in this solution.

[Docs](https://docs.aws.amazon.com/solutions/latest/video-on-demand/overview.html)

**Comment by tomnight** [comment]
Sorry for the delay, 

Cost will depend on the resolution of you source video (which will determine which template is used) and if you use mediapackage. Details on the pricing can be found here: https://aws.amazon.com/mediaconvert/pricing/

Billing is based on outputs so for example the 720p template includes
1 HD MP4
3 HD HLS, DASH (6 total)
4 SD HLS, DASH (8 total)

So you would be billed by for 7 HD outputs and 8 SD outputs.

**Comment by ebinbabu** [comment]
Thank you @tomnight
